Aide_Text_HaventCaughtEnoughMonsForItem::
	.string "Vaatame…\n"
	.string "Oih! Sa oled püüdnud vaid\l"
	.string "{STR_VAR_3} liiki POKéMONi!\p"
	.string "Sul on vaja {STR_VAR_1} liiki,\n"
	.string "et saada {STR_VAR_2}.$"
Aide_Text_GetEnoughMonsComeBackForItem::
	.string "…Ah. Nii.\p"
	.string "Kui sul on {STR_VAR_1} liiki POKéMONi,\n"
	.string "tule tagasi {STR_VAR_2} järele.$"
Aide_Text_DontHaveAnyRoomForItem::
	.string "Oh! Näen, et sul pole ruumi\n"
	.string "{STR_VAR_2} jaoks.$"
