@ Flavor text for interacting with various background objects

Text_Bookshelf::
.string "See on täis POKéMONi\n"
.string "raamatuid.$"

Text_NothingButPokemonBooks::
.string "Riiulisse on ritta seatud\n"
.string "ainult POKéMONi raamatud.$"

Text_ATownMap::
.string "LINNA KAART.$"

Text_PokeMartShelf::
.string "Vau!\n"
.string "Nii palju POKéMONi kraami!$"

Text_DishesPlatesNeatlyLinedUp::
.string "Nõud ja taldrikud on kenasti\n"
.string "ritta seatud.$"

Text_Kitchen::
.string "Siin lõhnab maitsvalt!\n"
.string "Keegi on siin kokanud.$"

Text_Dresser::
.string "See on kenasti tehtud kummut.\n"
.string "Sellesse mahub palju asju.$"

Text_Snacks::
.string "Siin on hunnik suupisteid.$"

Text_PokemartSign::
.string "Kõik vajalikud esemed ühest kohast!\n"
.string "POKéMON MART$"

Text_PokecenterSign::
.string "Tee oma POKéMON terveks!\n"
.string "POKéMON CENTER$"

Text_Indigo_UltimateGoal::
.string "INDIGO PLATEAU\p"
.string "TREENERITE ülim eesmärk!\n"
.string "POKéMON LIIGA PEAKORTER$"

Text_Indigo_HighestAuthority::
.string "INDIGO PLATEAU\p"
.string "Kõrgeim POKéMONi võimukandja!\n"
.string "POKéMON LIIGA PEAKORTER$"

Text_Food::
.string "See peaks olema täis igasugu\n"
.string "maitsvaid söögikraame.$"

Text_Blueprints::
.string "See on mingit sorti joonis.\n"
.string "See on täis skeeme ja teksti.$"

Text_Painting::
.string "See on ilus pilt ühest POKéMONist.\n"
.string "Tundub, et ta tunneb end hästi.$"

Text_PowerPlantMachine::
.string "Mis masin see küll olla võiks?\n"
.string "Parem mitte sellega jaurata!$"

Text_Telephone::
.string "See on telefon.\n"
.string "Parem mitte seda kasutada.$"

Text_Computer::
.string "See on täis keerulisi sõnu ja\n"
.string "numbreid, millel ei oma mingit mõtet…$"

Text_AdvertisingPoster::
.string "See on igasuguste toodete\n"
.string "reklaamplakat.$"

Text_TastyFood::
.string "Ooh, see lõhnab maitsvalt!\n"
.string "See võib kõhu korisema panna!$"

Text_TrashBin::
.string "Selle sees…\n"
.string "……\p"
.string "Siin pole mitte midagi!$"

Text_Cup::
.string "See on tass, millel on POKéMONi\n"
.string "märk.$"

Text_PolishedWindow::
.string "Aken on väga hästi puhtaks pestud.$"

Text_BeautifulSkyWindow::
.string "Akna taga…\p"
.string "Taevas näeb välja muinasjutuliselt\n"
.string "ilus.$"

Text_BlinkingLights::
.string "Erivärvilised tuled vilguvad\n"
.string "sisse ja välja.$"

Text_NeatlyLinedUpTools::
.string "Igasugused tööriistad on kenasti\n"
.string "ritta seatud.$"

Text_ImpressiveMachine::
.string "See on mingit sorti masin.\n"
.string "See on tõeliselt muljetavaldav.$"

Text_VideoGame::
.string "See on uusim videomäng!\n"
.string "See näeb kindlasti lõbus välja!$"

Text_Burglary::
.string "Siin on ilmselged sissemurdmise\n"
.string "jäljed…$"

Text_PlayerFacingTVScreen::
.string "Teleris on POKéMON!\n"
.string "Tundub, et tal on lõbus.$"
