Help_Text_WhatShouldIDo::
	.string "Mida peaksin tegema?$"

Help_Text_HowDoIDoThis::
	.string "Kuidas seda teha?$"

Help_Text_WhatDoesThisTermMean::
	.string "Mida see termin tähendab?$"

Help_Text_AboutThisGame::
	.string "Selle mängu kohta$"

Help_Text_TypeMatchupList::
	.string "Tüüpide vastavuste nimekiri$"

Help_Text_Exit::
	.string "VÄLJU$"

Help_Text_Cancel::
	.string "TÜHISTA$"

Help_Text_TryDoingItOnYourOwn::
	.string "じぶんの ちからで やってみよう！$"

Help_Text_DescWhatShouldIDo::
	.string "Vali, et saada vihjeid keeruliste\n"
	.string "olukordade lahendamiseks.$"

Help_Text_DescHowDoIDoThis::
	.string "Antakse üksikasjalikud juhised\n"
	.string "erinevate toimingute kohta.$"

Help_Text_DescWhatDoesThisTermMean::
	.string "Antakse üksikasjalikud selgitused\n"
	.string "mängus esinevate terminite kohta.$"

Help_Text_DescAboutThisGame::
	.string "Antakse üksikasjalikud selgitused\n"
	.string "selle mängu kohta.$"

Help_Text_DescTypeMatchupList::
	.string "Loetletakse POKéMONi tüüpide\n"
	.string "ja liigutuste vastavused.$"

Help_Text_DescExit::
	.string "Vali, et ABIsüsteemist väljuda.$"

Help_Text_Greetings::
	.string "Tere! Siin on ABIsüsteem.\n"
	.string "Kutsu mind igal ajal ja igal pool\l"
	.string "vajutades nuppu L või R.\l"
	.string "Abiinfo muutub vastavalt olukorrale,\l"
	.string "seega kontrolli seda sageli.$"

Help_Text_PlayingForFirstTime::
	.string "Mängin esimest korda. Appi!$"

Help_Text_WhatShouldIBeDoing::
	.string "Mida ma peaksin tegema?$"

Help_Text_CantGetOutOfRoom::
	.string "Ma ei saa toast välja!$"

Help_Text_CantFindPersonIWant::
	.string "Ma ei leia inimest, keda otsin.$"

Help_Text_TalkedToEveryoneNowWhat::
	.string "Rääkisin kõigiga. Mis edasi?$"

Help_Text_SomeoneBlockingMyWay::
	.string "Keegi tõkestab mu teed!$"

Help_Text_ICantGoOn::
	.string "Ma ei saa edasi minna!$"

Help_Text_OutOfThingsToDo::
	.string "Mul pole enam midagi teha.$"

Help_Text_WhatHappenedToItemIGot::
	.string "Mis juhtus esemega, mille sain?$"

Help_Text_WhatAreMyAdventureBasics::
	.string "Mis on mu seikluse põhitõed?$"

Help_Text_HowAreRoadsForestsDifferent::
	.string "Mille poolest erinevad teed ja metsad?$"

Help_Text_HowAreCavesDifferent::
	.string "Mille poolest on koobas teistsugune?$"

Help_Text_HowDoIProgress::
	.string "Kuidas edasi liikuda?$"

Help_Text_WhenCanIUseItem::
	.string "Millal saan esemeid kasutada?$"

Help_Text_WhatsABattle::
	.string "Mis on lahing?$"

Help_Text_HowDoIPrepareForBattle::
	.string "Kuidas lahinguks valmistuda?$"

Help_Text_WhatIsAMonsVitality::
	.string "Mis on POKéMONi elujõud?$"

Help_Text_MyMonsAreHurt::
	.string "Mu POKéMONid on vigastatud!$"

Help_Text_WhatIsStatusProblem::
	.string "Mis on staatusprobleem?$"

Help_Text_WhatHappensIfAllMyMonsFaint::
	.string "Mis juhtub, kui kõik mu POKéMONid minestuvad?$"

Help_Text_CantCatchMons::
	.string "Ma ei suuda POKéMONe püüda!$"

Help_Text_RanOutOfPotions::
	.string "Mul said ELIKSIRID otsa.$"

Help_Text_CanIBuyPokeBalls::
	.string "Kas saan osta POKéPALLE?$"

Help_Text_WhatsATrainer::
	.string "Mis on TREENIJA?$"

Help_Text_HowDoIWinAgainstTrainer::
	.string "Kuidas võita TREENIJAT?$"

Help_Text_WhereDoMonsAppear::
	.string "Kus POKéMONid ilmuvad?$"

Help_Text_WhatAreMoves::
	.string "Mis on POKéMONi liigutused?$"

Help_Text_WhatAreHiddenMoves::
	.string "Mis on PEIDETUD liigutused?$"

Help_Text_WhatMovesShouldIUse::
	.string "Milliseid liigutusi peaksin kasutama?$"

Help_Text_WantToAddMoreMoves::
	.string "Tahan lisada rohkem liigutusi.$"

Help_Text_WantToMakeMonStronger::
	.string "Tahan oma POKéMONi tugevamaks teha.$"

Help_Text_FoeMonsTooStrong::
	.string "Vaenlase POKéMONid on liiga tugevad!$"

Help_Text_WhatDoIDoInCave::
	.string "Mida teha koopas?$"

Help_Text_NothingIWantToKnow::
	.string "Pole midagi, mida teada tahaksin!$"

Help_Text_WhatsPokemonCenter::
	.string "Mis on POKéMONi KESKUS?$"

Help_Text_WhatsPokemonMart::
	.string "Mis on POKéMONi POOD?$"

Help_Text_WantToEndGame::
	.string "Tahan mängu lõpetada.$"

Help_Text_WhatsAMon::
	.string "Mis on POKéMON?$"

Help_Text_WhatIsThatPersonLike::
	.string "Milline on see inimene?$"

Help_Text_WhatDoesHiddenMoveDo::
	.string "Mida teeb PEIDETUD liigutus?$"

Help_Text_WhatDoIDoInSafari::
	.string "Mida teha SAFARIMÄNGUS?$"

Help_Text_WhatAreSafariRules::
	.string "Mis on SAFARIMÄNGU reeglid?$"

Help_Text_WantToEndSafari::
	.string "Tahan selle SAFARIMÄNGU lõpetada!$"

Help_Text_WhatIsAGym::
	.string "Mis on SPORDISAAL?$"

Help_Text_AnswerPlayingForFirstTime::
	.string "Sa saad peategelaseks,\n"
	.string "uurides POKéMONi maailma.\l"
	.string "Inimestega rääkides ja mõistatusi\l"
	.string "lahendades avanevad sulle uued teed.\l"
	.string "Püüdle eesmärgi poole koos oma\l"
	.string "suurepäraste POKéMONidega.$"

Help_Text_AnswerWhatShouldIBeDoing::
	.string "Kui kohtad teist inimest, mine tema\n"
	.string "juurde ja vajuta nuppu A.\l"
	.string "See paneb ta rääkima ja suhtlema\l"
	.string "sinu tegelasega. Samuti saad\l"
	.string "erinevaid esemeid ja objekte\l"
	.string "samal viisil uurida. Räägi inimestega\l"
	.string "ja kontrolli asju sageli.$"

Help_Text_AnswerCantGetOutOfRoom::
	.string "Trepil või hoone väljapääsul on\n"
	.string "punane matt. Liiguta oma tegelane\l"
	.string "punase mati peale seisma.\l"
	.string "Vajuta {PLUS} juhtkangil treppide\l"
	.string "või väljapääsu suunas,\l"
	.string "et edasi liikuda.$"

Help_Text_AnswerCantFindPersonIWant::
	.string "See pole midagi, mille pärast\n"
	.string "liiga palju muretseda.\l"
	.string "Räägi teiste inimestega, kontrolli\l"
	.string "silte, uuri asju jne.\l"
	.string "Mõnikord võib olla vaja lihtsalt\l"
	.string "liikuda uude linna või kohta.$"

Help_Text_AnswerTalkedToEveryoneNowWhat::
	.string "Proovi liikuda edasi uuele teele,\n"
	.string "linna või kohta.$"

Help_Text_AnswerSomeoneBlockingMyWay::
	.string "Linnas või hoone sees võib olla\n"
	.string "midagi, mis selle põhjustab.\l"
	.string "Proovi piirkonna inimestega\l"
	.string "uuesti rääkida. Kui neil on lahendamist\l"
	.string "vajav probleem, võid pead aidata.\l"
	.string "Seejärel proovi uuesti rääkida\l"
	.string "sinul teed tõkestava isikuga.$"

Help_Text_AnswerICantGoOn::
	.string "Proovi rääkida inimestega, minnes\n"
	.string "nende juurde ja vajutades nuppu A.\l"
	.string "Samuti proovi uurida kummalisi puid\l"
	.string "ja veidraid kive nupuga A.\l"
	.string "Vajuta {PLUS} juhtkangil ja proovi minna\l"
	.string "ka kohtadesse, mis näivad läbimatud.$"

Help_Text_AnswerOutOfThingsToDo::
	.string "Proovi minna kohtadesse, kus sa\n"
	.string "pole veel käinud.\l"
	.string "Samuti kontrolli kõike, mis tundub\l"
	.string "kahtlane, vajutades nuppu A.$"

Help_Text_AnswerWhatHappenedToItemIGot::
	.string "Iga ese, mille sulle teine tegelane\n"
	.string "annab, läheb su KOTTI.\l"
	.string "Ese sorteeritakse automaatselt\l"
	.string "ja paigutatakse ühte kolmest taskust.\l"
	.string "Koti kasutamise juhiste saamiseks\l"
	.string "vaata ABIsüsteemi rubriiki\l"
	.string "Kuidas seda teha?.$"

Help_Text_AnswerWhatAreMyAdventureBasics::
	.string "Kui POKéMONid saavad lahingus vigastada,\n"
	.string "vii nad POKéMONi KESKUSESSE ja\l"
	.string "lase personal neid ravida.\l"
	.string "Harju mängu salvestama ja\l"
	.string "edu kirja panema.\l"
	.string "Varusta end ravimiainetega\l"
	.string "POKéMONi POODIDEST enne kaugemat reisi.$"

Help_Text_AnswerHowAreRoadsForestsDifferent::
	.string "Metsad on põhimõtteliselt samad\n"
	.string "mis teed, kuid võivad olla labürindid.\l"
	.string "Kõigist metsadest pääseb välja,\l"
	.string "seega ära anna alla, kui eksid.$"

Help_Text_AnswerHowAreCavesDifferent::
	.string "Koobad on pimedad ja ohtlikud.\n"
	.string "Metsikud POKéMONid võivad ilmuda igal pool.\l"
	.string "Hädaolukorras kiirusta\l"
	.string "POKéMONi KESKUSESSE või kasuta esemeid.\l"
	.string "Mõne kooopa taga ootavad avastamist\l"
	.string "uued linnad, seega ära anna alla.$"

Help_Text_AnswerHowDoIProgress::
	.string "Mängu eesmärk on treenida oma\n"
	.string "POKéMONe ja edasi liikuda.\l"
	.string "Pead koguma infot ja lahendama\l"
	.string "probleeme. Näiteks, mida vajad\l"
	.string "takistusest mööda saamiseks?\l"
	.string "Mis saaks selle tõkestava\l"
	.string "isiku teelt kõrvale saata?$"

Help_Text_AnswerWhenCanIUseItem::
	.string "Esemeid on mitut liiki.\n"
	.string "Mõnda saab kasutada ainult väljas.\l"
	.string "Mõned on ainult lahingus kasutamiseks.\l"
	.string "Mõnda saab kasutada igal ajal.\l"
	.string "Proovi eset kasutada - kui seda ei saa\l"
	.string "kasutada, saad vastava teate.$"

Help_Text_AnswerWhatsABattle::
	.string "Lahingus püüavad POKéMONid vähendada\n"
	.string "teineteise elujõudu, mida väljendatakse\l"
	.string "ELuna. Kui POKéMONi EL langeb nullini,\l"
	.string "minestub ta ning teine POKéMON\l"
	.string "võidab. Lahingu võites teenivad\l"
	.string "POKéMONid KOGEMUSEpunkte, mis\l"
	.string "aitavad neil tasemeid tõusta.$"

Help_Text_AnswerHowDoIPrepareForBattle::
	.string "Kõigepealt ravitse oma seltskonna\n"
	.string "POKéMONid täielikult (POKéMONid,\l"
	.string "kes on sinuga) mõnes\l"
	.string "POKéMONi KESKUSES.\l"
	.string "Osta ka ravimiained hädaolukordadeks\l"
	.string "POKéMONi POEST.$"

Help_Text_AnswerWhatIsAMonsVitality::
	.string "POKéMONi elujõudu väljendatakse ELina.\n"
	.string "Kui POKéMON saab lahingus vigastada, EL\l"
	.string "väheneb. Kui EL langeb nullini,\l"
	.string "minestub POKéMON.\l"
	.string "Ravi vigastatud ja minestunud POKéMONid\l"
	.string "POKéMONi KESKUSES või esemete abil.$"

Help_Text_AnswerMyMonsAreHurt::
	.string "POKéMONi KESKUS on nagu võõrastemaja\n"
	.string "POKéMONidele. See ravib POKéMONe\l"
	.string "täielikult kõigist staatusprobleemidest\l"
	.string "ja taastab nende ELi erilise masina abil.\l"
	.string "See teenus on tasuta, seega harju\l"
	.string "oma POKéMONe sageli ravimas käima.$"

Help_Text_AnswerWhatIsStatusProblem::
	.string "Staatusprobleem viitab vaevusele,\n"
	.string "mille vaenlase rünnak POKéMONile\l"
	.string "põhjustab. Nende hulka kuuluvad\l"
	.string "põletused, halvatus, mürgistus,\l"
	.string "uni ja külmutamine. Neid saab ravida\l"
	.string "külastades POKéMONi KESKUST või\l"
	.string "kasutades sobivat eset.$"

Help_Text_AnswerWhatHappensIfAllMyMonsFaint::
	.string "Kui kõik sinu seltskonna POKéMONid\n"
	.string "(kõik sinuga olevad POKéMONid) minestuvad,\l"
	.string "kaotad osa RAHAST ning sind\l"
	.string "viiakse koju või POKéMONi\l"
	.string "KESKUSESSE. Vähenda seda ohtu, külastades\l"
	.string "POKéMONi KESKUSEID sageli. Samuti\l"
	.string "harju sageli salvestama.$"

Help_Text_AnswerCantCatchMons::
	.string "Kui metsik POKéMON põgeneb POKéPALLIST,\n"
	.string "on ta ilmselgelt veel elujõuline.\l"
	.string "Proovi tema ELi veelgi vähendada\l"
	.string "ning nõrgenda teda halvatuse või unega\l"
	.string "enne püüdmist.\l"
	.string "Kui POKéPALL kaua kõigub,\l"
	.string "on püüdmine peaaegu õnnestunud!$"

Help_Text_AnswerRanOutOfPotions::
	.string "On olemas poed, mida tuntakse\n"
	.string "POKéMONi POODIDENA, kus müüakse esemeid.\l"
	.string "POKéMONi POODE ei leidu\l"
	.string "teedel, metsades ega koobaste.\l"
	.string "Varusta end vajalike esemetega,\l"
	.string "kui külastad linna POKéMONi POEGA.$"

Help_Text_AnswerCanIBuyPokeBalls::
	.string "POKéPALLE saab osta igast\n"
	.string "POKéMONi POEST igas linnas.\l"
	.string "POKéMONi POODE ei leidu\l"
	.string "teedel, metsades ega koobaste.\l"
	.string "Varusta end POKéPALLIDEGA,\l"
	.string "kui külastad linna POKéMONi POEGA.$"

Help_Text_AnswerWhatsATrainer::
	.string "TREENIJA on inimene, kes kasvatab\n"
	.string "POKéMONe lahingute kaudu.\l"
	.string "TREENIJAD väljakutsuvad sind\l"
	.string "kus iganes nad on - teel,\l"
	.string "metsades, koopastes, kõikjal.\l"
	.string "Kui teie silmad kohtuvad, pead\l"
	.string "nende väljakutse vastu võtma. Ole ettevaatlik!$"

Help_Text_AnswerHowDoIWinAgainstTrainer::
	.string "TREENIJA lahingus võitmiseks kasuta\n"
	.string "POKéMONe, kellel on tüübieelised\l"
	.string "vaenlase POKéMONide üle. Võid kasutada\l"
	.string "ka hästi treenitud POKéMONe\l"
	.string "ülivõimsa jõuga. Vaenlase POKéMONide\l"
	.string "arvuline ülekaal on samuti\l"
	.string "ilmne taktika.$"

Help_Text_AnswerWhereDoMonsAppear::
	.string "Metsikud POKéMONid ilmuvad pikas rohus,\n"
	.string "teedel ja metsades. Nad ilmuvad\l"
	.string "kõikjal pimeda koopa sees.\l"
	.string "Linnades pole metsikuid POKéMONe ega\l"
	.string "TREENIJAID, seega on need turvalised kohad.$"

Help_Text_AnswerWhatAreMoves::
	.string "POKéMONid võivad õppida kuni neli erinevat\n"
	.string "tehnikat ehk liigutust. On suur\l"
	.string "valik liigutusi, sealhulgas rünnakuid ja\l"
	.string "erimõjuga liigutusi. Õpitavate liigutuste\l"
	.string "liigid erinevad iga POKéMONi puhul.\l"
	.string "Mõnda liigutust saab masinatelt õppida.$"

Help_Text_AnswerWhatAreHiddenMoves::
	.string "PEIDETUD liigutused on eriti olulised\n"
	.string "su seiklusele. Sellise liigutuse\l"
	.string "kasutamiseks väljaspool lahingut ava\l"
	.string "POKéMONi MENÜÜ ja lase seda liigutust\l"
	.string "tundval POKéMONil seda kasutada.\l"
	.string "Minestunud POKéMON võib kasutada\l"
	.string "PEIDETUD liigutust väljaspool lahingut.$"

Help_Text_AnswerWhatMovesShouldIUse::
	.string "Vali VÕITLE ja ilmub liigutuste MENÜÜ.\n"
	.string "Kaalu tüübikombinatsioone ning kasuta\l"
	.string "kõige tõhusamaid liigutusi. Saad\l"
	.string "liigutuste mõjusid kontrollida avades\l"
	.string "POKéMON, valides POKéMONi, avades\l"
	.string "KOKKUVÕTE ning seejärel\l"
	.string "POKéMONi OSKUSED.$"

Help_Text_AnswerWantToAddMoreMoves::
	.string "POKéMON saab õppida maksimaalselt neli\n"
	.string "liigutust. Need õpitakse selgeks, kui\l"
	.string "POKéMON tasemeid tõuseb. Samuti saab\l"
	.string "talle liigutust õpetada TM-i (Tehniline\l"
	.string "Masin) või HM-i (Peidetud Masin) abil.\l"
	.string "On ka inimesi, kes liigutusi õpetavad.$"

Help_Text_AnswerWantToMakeMonStronger::
	.string "Võti oma POKéMONide tugevamaks tegemiseks\n"
	.string "on sageli lahinguid pidada ja võita.\l"
	.string "Võitudes kogutud KOGEMUSE punktid\l"
	.string "kogunevad, et tõsta lahingus osalenud\l"
	.string "POKéMONide taset. Võitle sageli\l"
	.string "metsikute POKéMONidega, et\l"
	.string "oma seltskonda tasemeid tõsta.$"

Help_Text_AnswerFoeMonsTooStrong::
	.string "Kui vaenlased on liiga tugevad, proovi\n"
	.string "oma POKéMONide taset veelgi tõsta.\l"
	.string "Mine tagasi tulnud teed ja võitle\l"
	.string "metsikute POKéMONidega oma seltskonna\l"
	.string "taseme tõstmiseks. Võid ka võidelda\l"
	.string "TREENIJATEGA, kellega pole veel\l"
	.string "lahingut pidanud.$"

Help_Text_AnswerWhatDoIDoInCave::
	.string "Erinevalt teedest ja metsadest võivad\n"
	.string "koopastes metsikud POKéMONid ilmuda igal pool.\l"
	.string "Kui su POKéMONid saavad koopas vigastada,\l"
	.string "kiirusta POKéMONi KESKUSESSE või kasuta\l"
	.string "nende ravimiseks kohe esemeid.\l"
	.string "Koopastes õnne kiusamine on väga ohtlik.$"

Help_Text_AnswerNothingIWantToKnow::
	.string "Usalda oma teadmisi ja jõudu.\n"
	.string "Usu endasse ja leia oma tee!$"

Help_Text_AnswerWhatsPokemonCenter::
	.string "POKéMONi KESKUST tunneb ära punase katuse\n"
	.string "ja P.K sildi järgi. Iga\l"
	.string "POKéMONi KESKUS pakub selliseid teenuseid\l"
	.string "nagu POKéMONide täielik ravimine ja tasuta\l"
	.string "arvuti kasutamine - see on su reisidel\l"
	.string "hädavajalik. Ülakorrusel on\l"
	.string "sõpradega ühenduse loomise rajatised.$"

Help_Text_AnswerWhatsPokemonMart::
	.string "POKéMONi POODI tunneb ära sinise katuse\n"
	.string "ja POOD sildi järgi.\l"
	.string "Esemeid saab osta ja müüa igast\l"
	.string "POKéMONi POEST. Mõned POED pakuvad\l"
	.string "esemeid, mis on saadaval ainult nende linnas.$"

Help_Text_AnswerWantToEndGame::
	.string "Saad mängu turvaliselt lõpetada\n"
	.string "valides MENÜÜST SALVESTA.\l"
	.string "Pärast salvestamist saab mängu\l"
	.string "turvaliselt välja lülitada. Mängu\l"
	.string "uuesti käivitades saad jätkata\l"
	.string "sealt, kus viimati salvestasid.$"

Help_Text_AnswerWhatsAMon::
	.string "POKéMONid on elusolendid, kelle kohta\n"
	.string "on palju mõistatusi lahendamata. Neid\l"
	.string "võib näha rohus, meres ja koopastes.\l"
	.string "Nad näivad kuuletuvat neid\l"
	.string "püüdnud TREENIJATE soovidele.$"

Help_Text_AnswerWhatIsThatPersonLike::
	.string "Kasuta KUULSUSEKONTROLLIJAT\n"
	.string "oma KOTI VÕTMEESEMETE hulgas.\l"
	.string "See võib anda vihjeid - proovi järele.$"

Help_Text_AnswerWhatDoesHiddenMoveDo::
	.string "PEIDETUD liigutust õpetatakse POKéMONile\n"
	.string "HM-i (Peidetud Masina) abil.\l"
	.string "PEIDETUD liigutus on seiklusel\l"
	.string "oluline abi. Näiteks ühega saab\l"
	.string "pimedad koobad valgustada. Teine\l"
	.string "lõikab väikseid puid. On ka üks,\l"
	.string "millega veepinnal liikuda, ja nii edasi.$"

Help_Text_AnswerWhatDoIDoInSafari::
	.string "Proovi metsikuid POKéMONe püüda\n"
	.string "visates erilisi SAFARIPALLE.\l"
	.string "Võid ka leitud esemeid endale jätta.$"

Help_Text_AnswerWhatAreSafariRules::
	.string "Sinu SAFARIMÄNG lõpeb, kui oled\n"
	.string "teatud vahemaa läbinud või kõik\l"
	.string "SAFARIPALLID visanud.\l"
	.string "Ava MENÜÜ, et kontrollida\l"
	.string "järelejäänud sammude arvu ja SAFARIPALLE.$"

Help_Text_AnswerWantToEndSafari::
	.string "Kui soovid SAFARIMÄNGU\n"
	.string "enneaegselt lõpetada, ava MENÜÜ\l"
	.string "ja vali loendi ülaosast LOOBU.$"

Help_Text_AnswerWhatIsAGym::
	.string "POKéMONi SPORDISAALE haldab\n"
	.string "POKéMONi LIIGA ning need on\l"
	.string "TREENIJATE treeningkohad. Neid leidub\l"
	.string "üle maa linnades ja alevites.\l"
	.string "Iga saali juhib LIIDER, kes on\l"
	.string "väga oskuslik TREENIJA. Võida\l"
	.string "LIIDER, et koguda MÄRK.$"

Help_Text_UsingPokedex::
	.string " POKéDEXi kasutamine$"

Help_Text_UsingPokemon::
	.string " POKéMONi kasutamine$"

Help_Text_UsingSummary::
	.string "  KOKKUVÕTTE kasutamine$"

Help_Text_UsingSwitch::
	.string "  VAHETUSE kasutamine$"

Help_Text_UsingItem::
	.string "  ESEME kasutamine$"

Help_Text_UsingBag::
	.string " KOTI kasutamine$"

Help_Text_UsingAnItem::
	.string "  Eseme kasutamine$"

Help_Text_UsingKeyItem::
	.string "  Võtmeeseme kasutamine$"

Help_Text_UsingPokeBall::
	.string "  POKéPALLI kasutamine$"

Help_Text_UsingPlayer::
	.string " {PLAYER} kasutamine$"

Help_Text_UsingSave::
	.string " SALVESTUSE kasutamine$"

Help_Text_UsingOption::
	.string " SÄTETE kasutamine$"

Help_Text_UsingPotion::
	.string "    ELIKSIIRI kasutamine$"

Help_Text_UsingTownMap::
	.string "    LINNAKAARDI kasutamine$"

Help_Text_UsingTM::
	.string "    TM-i kasutamine$"

Help_Text_UsingHM::
	.string "    HM-i kasutamine$"

Help_Text_UsingMoveOutsideOfBattle::
	.string "Liigutuse kasutamine väljaspool lahingut$"

Help_Text_RidingBicycle::
	.string "    JALGRATTAGA sõitmine$"

Help_Text_EnteringName::
	.string "Nime sisestamine$"

Help_Text_UsingPC::
	.string "Arvuti kasutamine$"

Help_Text_UsingBillsPC::
	.string " {STR_VAR_1} ARVUTI kasutamine$"

Help_Text_UsingWithdraw::
	.string "  VÄLJAVÕTMISE kasutamine$"

Help_Text_UsingDeposit::
	.string "  HOIUSTAMISE kasutamine$"

Help_Text_UsingMove::
	.string "  LIIGUTAMISE kasutamine$"

Help_Text_MovingItems::
	.string "  Esemete liigutamine$"

Help_Text_UsingPlayersPC::
	.string " {PLAYER} ARVUTI kasutamine$"

Help_Text_UsingWithdrawItem::
	.string "  ESEME VÄLJAVÕTMISE kasutamine$"

Help_Text_UsingDepositItem::
	.string "  ESEME HOIUSTAMISE kasutamine$"

Help_Text_UsingMailbox::
	.string "  POSTKASTI kasutamine$"

Help_Text_UsingProfOaksPC::
	.string " PROF. TAMME ARVUTI kasutamine$"

Help_Text_OpeningMenu::
	.string "MENÜÜ avamine$"

Help_Text_UsingFight::
	.string " VÕITLEMISE kasutamine$"

Help_Text_UsingPokemon2::
	.string " POKéMONi kasutamine$"

Help_Text_UsingShift::
	.string "  VAHETUSE kasutamine$"

Help_Text_UsingSummary2::
	.string "  KOKKUVÕTTE kasutamine$"

Help_Text_UsingBag2::
	.string " KOTI kasutamine$"

Help_Text_ReadingPokedex::
	.string " POKéDEXi lugemine$"

Help_Text_UsingHomePC::
	.string "Koduse arvuti kasutamine$"

Help_Text_UsingItemStorage::
	.string "Esemete hoiustamissüsteemi kasutamine$"

Help_Text_UsingWithdrawItem2::
	.string "  ESEME VÄLJAVÕTMISE kasutamine$"

Help_Text_UsingDepositItem2::
	.string "  ESEME HOIUSTAMISE kasutamine$"

Help_Text_UsingMailbox2::
	.string "POSTKASTI kasutamine$"

Help_Text_UsingRun::
	.string " PÕGENEMISE kasutamine$"

Help_Text_RegisterKeyItem::
	.string "  Võtmeeseme REGISTREERIMINE$"

Help_Text_UsingBall::
	.string " PALLI kasutamine$"

Help_Text_UsingBait::
	.string " SÖÖDA kasutamine$"

Help_Text_UsingRock::
	.string " KIVI kasutamine$"

Help_Text_UsingHallOfFame::
	.string " KUULSUSTEHALLI kasutamine$"

Help_Text_HowToUsePokedex::
	.string "{CIRCLE_1} Vali MENÜÜST POKéDEX.\n"
	.string "{CIRCLE_2} Vali POKéMONe käskudega nagu\n"
	.string "   POKéMONIDE NIMEKIRI,\n"
	.string "   POKéMONIDE ELUPAIGAD ja\n"
	.string "   OTSING.\n"
	.string "{CIRCLE_3} Vali POKéMON üksikasjaliku\n"
	.string "   teabe saamiseks.$"

Help_Text_HowToUsePokemon::
	.string "{CIRCLE_1} Vali MENÜÜST POKéMON.\n"
	.string "{CIRCLE_2} Vali POKéMON oma selskonnast.\n"
	.string "{CIRCLE_3} Vali KOKKUVÕTE, VAHETA\n"
	.string "   või ESE.$"

Help_Text_HowToUseSummary::
	.string "{CIRCLE_1} Vali KOKKUVÕTE.\n"
	.string "{CIRCLE_2} Vajuta {PLUS} juhtkangil vasakule\n"
	.string "   või paremale teabe kontrollimiseks:\n"
	.string "   POKéMONi INFO\n"
	.string "   POKéMONi OSKUSED\n"
	.string "   TEADAOLEVAD LIIGUTUSED$"

Help_Text_HowToUseSwitch::
	.string "{CIRCLE_1} Vali POKéMON, keda soovid\n"
	.string "   ümber vahetada.\n"
	.string "{CIRCLE_2} Vali VAHETA.\n"
	.string "{CIRCLE_3} Vali POKéMON, kellega esimene\n"
	.string "   vahetada.\n"
	.string "Ekraani vasakul olev POKéMON\n"
	.string "läheb lahingusse esimesena.$"

Help_Text_HowToUseItem::
	.string "{CIRCLE_1} Vali ESE.\n"
	.string "{CIRCLE_2} Vali, kas soovid ANDA eseme\n"
	.string "   POKéMONile hoidmiseks,\n"
	.string "   või VÕTTA ese, mida ta hoiab.\n"
	.string "POKéMON ei saa hoida rohkem\n"
	.string "kui ühte eset!$"

Help_Text_HowToUseBag::
	.string "{CIRCLE_1} Vali MENÜÜST KOTT.\n"
	.string "{CIRCLE_2} Vajuta {PLUS} juhtkangil vasakule\n"
	.string "   või paremale, et kontrollida kategooriaid:\n"
	.string "   ESEMED\n"
	.string "   VÕTMEESEMED\n"
	.string "   POKéPALLID\n"
	.string "   Vajuta üles või alla, et valida ese.$"

Help_Text_HowToUseAnItem::
	.string "{CIRCLE_1} Vali ESEMETE tasku.\n"
	.string "{CIRCLE_2} Vajuta {PLUS} juhtkangil üles\n"
	.string "   või alla, et valida ese.\n"
	.string "{CIRCLE_3} Vali KASUTA, et valitud\n"
	.string "   eset kasutada.\n"
	.string "Mõnda eset ei saa kasutada sõltuvalt\n"
	.string "kohast ja/või olukorrast.$"

Help_Text_HowToUseKeyItem::
	.string "{CIRCLE_1} Vali VÕTMEESEMETE tasku.\n"
	.string "{CIRCLE_2} Vajuta {PLUS} juhtkangil üles\n"
	.string "   või alla, et valida võtmese.\n"
	.string "{CIRCLE_3} Vali KASUTA, et valitud\n"
	.string "   võtmeset kasutada.$"

Help_Text_HowToUsePokeBall::
	.string "{CIRCLE_1} Metsiku POKéMONiga võideldes\n"
	.string "   vali KOTI POKéPALLIDE tasku.\n"
	.string "{CIRCLE_2} Vajuta {PLUS} juhtkangil üles\n"
	.string "   või alla, et valida POKéPALL.\n"
	.string "{CIRCLE_3} Vali KASUTA, et valitud\n"
	.string "   POKéPALL visata.$"

Help_Text_HowToUsePlayer::
	.string "{CIRCLE_1} Vali MENÜÜST {PLAYER}.\n"
	.string "{CIRCLE_2} Sinu TREENIJA KAART kuvatakse\n"
	.string "   esiküljega üles koos põhiteabega.\n"
	.string "   Vajuta A, et kaarti ümber keerata.\n"
	.string "{CIRCLE_3} Kaardi tagaküljel leidub\n"
	.string "   mitmesuguseid andmeid.$"

Help_Text_HowToUseSave::
	.string "{CIRCLE_1} Vali MENÜÜST SALVESTA.\n"
	.string "{CIRCLE_2} Vali JAH ja su edenemine\n"
	.string "   salvestatakse salvestusfaili.\n"
	.string "Pärast salvestamist võid mängu välja\n"
	.string "lülitada. Mängu saab jätkata\n"
	.string "sealt, kus salvestasid.$"

Help_Text_HowToUseOption::
	.string "{CIRCLE_1} Vali MENÜÜST SÄTTED.\n"
	.string "{CIRCLE_2} Vajuta {PLUS} juhtkangil üles\n"
	.string "   või alla, et valida säte, seejärel\n"
	.string "   vajuta vasakule või paremale\n"
	.string "   seadistuste muutmiseks.\n"
	.string "{CIRCLE_3} Vali TÜHISTA või vajuta\n"
	.string "   muudatuste tegemise järel B.$"

Help_Text_HowToUsePotion::
	.string "{CIRCLE_1} Ava MENÜÜ.\n"
	.string "{CIRCLE_2} Vajuta {PLUS} juhtkangil üles\n"
	.string "   või alla ja vali KOTT.\n"
	.string "{CIRCLE_3} Vali ESEMETE taskust ELIKSIIR.\n"
	.string "{CIRCLE_4} Vali KASUTA.\n"
	.string "{CIRCLE_5} Vali POKéMON, keda ravida.$"

Help_Text_HowToUseTownMap::
	.string "{CIRCLE_1} Ava MENÜÜ.\n"
	.string "{CIRCLE_2} Vajuta {PLUS} juhtkangil üles\n"
	.string "   või alla ja vali KOTT.\n"
	.string "{CIRCLE_3} Vajuta vasakule või paremale,\n"
	.string "   et avada VÕTMEESEMETE tasku,\n"
	.string "   seejärel vajuta üles või alla,\n"
	.string "   et valida LINNAKAART.\n"
	.string "{CIRCLE_4} Vali KASUTA, et avada LINNAKAART.$"

Help_Text_HowToUseTM::
	.string "{CIRCLE_1} Ava MENÜÜ.\n"
	.string "{CIRCLE_2} Ava KOTI VÕTMEESEMETE tasku.\n"
	.string "{CIRCLE_3} AVA TM-i KARP.\n"
	.string "{CIRCLE_4} Vali TM ja KASUTA seda.\n"
	.string "{CIRCLE_5} Vali POKéMON, kes suudab selles\n"
	.string "   TM-is oleva liigutuse selgeks õppida.$"

Help_Text_HowToUseHM::
	.string "{CIRCLE_1} Ava MENÜÜ.\n"
	.string "{CIRCLE_2} Ava KOTI VÕTMEESEMETE tasku.\n"
	.string "{CIRCLE_3} AVA TM-i KARP.\n"
	.string "{CIRCLE_4} Vali HM ja KASUTA seda.\n"
	.string "{CIRCLE_5} Vali POKéMON, kes suudab selle selgeks õppida.\n"
	.string "HM-e on raske eemaldada - ole ettevaatlik!$"

Help_Text_HowToUseMoveOutsideOfBattle::
	.string "{CIRCLE_1} Ava MENÜÜ.\n"
	.string "{CIRCLE_2} Vali POKéMON.\n"
	.string "{CIRCLE_3} Vali POKéMON, kes teab\n"
	.string "   HM-i liigutust. Kasutatavad\n"
	.string "   HM-i liigutused kuvatakse siniselt.\n"
	.string "   Vali ja kasuta soovitud liigutust,\n"
	.string "   et takistus hävitada, lennata, surfata jne.$"

Help_Text_HowToRideBicycle::
	.string "{CIRCLE_1} Ava MENÜÜ. Ava KOTI\n"
	.string "   VÕTMEESEMETE tasku\n"
	.string "   ja vali JALGRATAS.\n"
	.string "{CIRCLE_2} JALGRATTAGA saab sõita\n"
	.string "   valides KASUTA. Samuti saad\n"
	.string "   selle koheseks kasutamiseks\n"
	.string "   vajutades SELECT REGISTREERIDA.$"

Help_Text_HowToEnterName::
	.string "{CIRCLE_1} Liiguta kursor soovitud tähele\n"
	.string "   {PLUS} juhtkangiga, seejärel vajuta\n"
	.string "   selle sisestamiseks A.\n"
	.string "{CIRCLE_2} Vajuta B, et samm tagasi minna.\n"
	.string "{CIRCLE_3} Vajuta SELECT, et lülituda\n"
	.string "   suur- ja väiketähtede vahel.\n"
	.string "{CIRCLE_4} Vajuta A nupul OK.$"

Help_Text_HowToUsePC::
	.string "{CIRCLE_1} Mine mõnda POKéMONi KESKUSESSE,\n"
	.string "   mine arvuti juurde ja vajuta A.$"

Help_Text_HowToUseBillsPC::
	.string "{CIRCLE_1} Vali arvutis {STR_VAR_1} ARVUTI.\n"
	.string "{CIRCLE_2} Vali kolmest ülemisest\n"
	.string "   MENÜÜ-kirjest, et pääseda\n"
	.string "   POKéMONide hoiustamissüsteemi.\n"
	.string "Kui püüad POKéMONi, kui sul on\n"
	.string "kuus seltskonnas, saadetakse POKéMON\n"
	.string "automaatselt süsteemi KASTI!$"

Help_Text_HowToUseWithdraw::
	.string "{CIRCLE_1} Vali {PLUS} juhtkangiga\n"
	.string "   avatud KASTIS POKéMON.\n"
	.string "{CIRCLE_2} Vali VÕTA VÄLJA, et POKéMON\n"
	.string "   KASTIST eemaldada ja oma\n"
	.string "   seltskonda lisada.\n"
	.string "POKéMONi ei saa välja võtta,\n"
	.string "kui sul on juba kuus POKéMONi!$"

Help_Text_HowToUseDeposit::
	.string "{CIRCLE_1} Vali {PLUS} juhtkangiga\n"
	.string "   POKéMON oma selskonnast.\n"
	.string "{CIRCLE_2} Vali HOIUSTA.\n"
	.string "{CIRCLE_3} Vali KAST, seejärel vajuta A,\n"
	.string "   et POKéMON salvestada.\n"
	.string "Kui sul on ainult üks POKéMON,\n"
	.string "ei saa teda salvestada!$"

Help_Text_HowToUseMove::
	.string "{CIRCLE_1} Vali avatud KASTIS POKéMON.\n"
	.string "{CIRCLE_2} Tõsta POKéMON üles valides\n"
	.string "   LIIGUTA ja liiguta teda kuhu\n"
	.string "   soovid {PLUS} juhtkangiga.\n"
	.string "{CIRCLE_3} Liiguta POKéMON KASTI nime\n"
	.string "   juurde ja vajuta vasakule või\n"
	.string "   paremale, et teise KASTI liikuda.$"

Help_Text_HowToMoveItems::
	.string "{CIRCLE_1} Hämaralt nähtavaid POKéMONe\n"
	.string "   saab panna eset hoidma, valides\n"
	.string "   POKéMONi ja vajutades A.\n"
	.string "{CIRCLE_2} Selgelt nähtavaid POKéMONe\n"
	.string "   saab panna nende hoitava eseme\n"
	.string "   teisele POKéMONile andma või\n"
	.string "   KOTTI tagastama A-nupuga.$"

Help_Text_HowToUsePlayersPC::
	.string "{CIRCLE_1} Vali arvutis {PLAYER} ARVUTI.\n"
	.string "{CIRCLE_2} Vali kas ESEMETE HOIUSTAMINE\n"
	.string "   või POSTKAST.\n"
	.string "Oma arvutisse saad asju hoiustada,\n"
	.string "kui su KOTT on täis. Samuti saad\n"
	.string "oma arvutis hoiustatud esemeid välja võtta.$"

Help_Text_HowToUseWithdrawItem::
	.string "{CIRCLE_1} Vali VÕTA ESE VÄLJA.\n"
	.string "{CIRCLE_2} Vali ese, mida välja võtta.\n"
	.string "{CIRCLE_3} Ese saab välja võetud ja\n"
	.string "   paigutatud KOTI ESEMETE taskusse.\n"
	.string "   Seda saab ka otse anda\n"
	.string "   POKéMONile hoidmiseks.$"

Help_Text_HowToUseDepositItem::
	.string "{CIRCLE_1} Vali HOIUSTA ESE.\n"
	.string "{CIRCLE_2} Vali {PLUS} juhtkangiga KOTIS\n"
	.string "   olev ese, mida hoiustada.\n"
	.string "{CIRCLE_3} Kui hoiustatavaid esemeid\n"
	.string "   on rohkem kui üks, sisesta\n"
	.string "   kogus {PLUS} juhtkangiga,\n"
	.string "   seejärel vajuta A.$"

Help_Text_HowToUseMailbox::
	.string "Kui POKéMONilt võetakse KIRI,\n"
	.string "viiakse see POSTKASTI. Kui tal pole\n"
	.string "KIRJA, ei saa POSTKASTI kasutada.\n"
	.string "{CIRCLE_1} Vali arvutis {PLAYER} ARVUTI.\n"
	.string "{CIRCLE_2} Vali POSTKAST, et KIRJU lugeda\n"
	.string "   või POKéMONil KIRI kaasas olla.$"

Help_Text_HowToUseProfOaksPC::
	.string "{CIRCLE_1} Vali arvutis PROF. TAMME ARVUTI.\n"
	.string "{CIRCLE_2} PROF. TAMM hindab sinu\n"
	.string "   POKéDEXit.\n"
	.string "Tema hinnangud peaksid andma vihjeid\n"
	.string "rohkemate POKéMONide püüdmiseks!$"

Help_Text_HowToOpenMenu::
	.string "{CIRCLE_1} Vajuta START.\n"
	.string "{CIRCLE_2} MENÜÜ avaneb paremal.\n"
	.string "{CIRCLE_3} Sõltuvalt olukorrast võib MENÜÜS\n"
	.string "   olla erinevaid rubriike.\n"
	.string "MENÜÜ ei avane teatud\n"
	.string "olukordades, näiteks rääkides,\n"
	.string "midagi tehes, lahingus jne.$"

Help_Text_HowToUseFight::
	.string "{CIRCLE_1} Vali VÕITLE.\n"
	.string "{CIRCLE_2} Vali üks näidatud liigutustest\n"
	.string "ja seda liigutust kasutatakse!$"

Help_Text_HowToUsePokemon2::
	.string "{CIRCLE_1} Vali POKéMON.\n"
	.string "{CIRCLE_2} Vali POKéMON oma selskonnast,\n"
	.string "   keda soovid kasutada.\n"
	.string "{CIRCLE_3} Kui sul on kaks või rohkem\n"
	.string "   POKéMONi, saab neid vahetada\n"
	.string "   valides VAHETA. Kontrolli\n"
	.string "   andmeid valides KOKKUVÕTE.$"

Help_Text_HowToUseShift::
	.string "See käsk vahetab lahingus oleva\n"
	.string "POKéMONi teise vastu sinu selskonnast.\n"
	.string "{CIRCLE_1} Vali POKéMON, keda saata välja.\n"
	.string "{CIRCLE_2} Vali VAHETA.\n"
	.string "{CIRCLE_3} Valitud POKéMON vahetab kohad\n"
	.string "   lahingus oleva POKéMONiga!$"

Help_Text_HowToUseSummary2::
	.string "{CIRCLE_1} Vali KOKKUVÕTE.\n"
	.string "{CIRCLE_2} Vajuta {PLUS} juhtkangil vasakule\n"
	.string "   või paremale, et kontrollida teavet:\n"
	.string "   POKéMONi INFO\n"
	.string "   POKéMONi OSKUSED\n"
	.string "   TEADAOLEVAD LIIGUTUSED$"

Help_Text_HowToUseBag2::
	.string "{CIRCLE_1} Vali KOTT.\n"
	.string "{CIRCLE_2} Vajuta {PLUS} juhtkangil vasakule\n"
	.string "   või paremale, et kontrollida kategooriaid:\n"
	.string "   ESEMED\n"
	.string "   VÕTMEESEMED\n"
	.string "   POKéPALLID\n"
	.string "   Vajuta üles või alla, et valida ese.$"

Help_Text_HowToReadPokedex::
	.string "{CIRCLE_1} POKéMONid, keda oled püüdnud,\n"
	.string "   tähistatakse POKéPALLI märgiga\n"
	.string "   POKéDEXi nimekirjas.\n"
	.string "{CIRCLE_2} Püütud POKéMON annab\n"
	.string "   suure hulga andmeid.\n"
	.if REVISION < 1
	.string "{CIRCLE_3} Vali ALA, et kuvada LINNAKAART\n"
	.string "   POKéMONi elupaiga(de)ga.$"
	.else
	.string "{CIRCLE_3} Vali JÄRGMISED ANDMED, et kuvada\n"
	.string "   LINNAKAART koos elupaiga(de)ga.$"
	.endif

Help_Text_HowToUseHomePC::
	.string "{CIRCLE_1} Mine koduse arvuti juurde,\n"
	.string "   seejärel vajuta A.\n"
	.string "{CIRCLE_2} Arvuti lülitub sisse.\n"
	.string "{CIRCLE_3} Vali kas ESEMETE HOIUSTAMINE\n"
	.string "   või POSTKAST.$"

Help_Text_HowToUseItemStorage::
	.string "{CIRCLE_1} Vali VÕTA ESE VÄLJA, et\n"
	.string "   arvutis hoiustatud ese välja võtta.\n"
	.string "{CIRCLE_2} Vali HOIUSTA ESE, et panna\n"
	.string "   ese KOTIST oma arvutisse.$"

Help_Text_HowToUseWithdrawItem2::
	.string "{CIRCLE_1} Vali VÕTA ESE VÄLJA.\n"
	.string "{CIRCLE_2} Vali ese, mida välja võtta.\n"
	.string "{CIRCLE_3} Ese saab välja võetud ja\n"
	.string "   paigutatud KOTI ESEMETE taskusse.\n"
	.string "   Seda saab ka otse anda\n"
	.string "   POKéMONile hoidmiseks.$"

Help_Text_HowToUseDepositItem2::
	.string "{CIRCLE_1} Vali HOIUSTA ESE.\n"
	.string "{CIRCLE_2} Vali {PLUS} juhtkangiga KOTIS\n"
	.string "   olev ese, mida hoiustada.\n"
	.string "{CIRCLE_3} Kui KOTIS pole midagi,\n"
	.string "   ei saa seda käsku kasutada!$"

Help_Text_HowToUseMailbox2::
	.string "Kui POKéMONilt võetakse KIRI,\n"
	.string "viiakse see POSTKASTI. Kui tal pole\n"
	.string "KIRJA, ei saa POSTKASTI kasutada.\n"
	.string "{CIRCLE_1} Vali KIRI nimepidi, et seda lugeda\n"
	.string "   või POKéMONil kaasas olla.$"

Help_Text_HowToUseRun::
	.string "TREENIJA lahingust ei saa PÕGENEDA!\n"
	.string "{CIRCLE_1} Metsiku POKéMONi eest saab PÕGENEDA.\n"
	.string "{CIRCLE_2} Põgenemise võimalus suureneb,\n"
	.string "   kui su lahingus olev POKéMON on kiire.$"

Help_Text_HowToRegisterKeyItem::
	.string "Võtmeset saab koheseks kasutamiseks\n"
	.string "SELECT-nupuga REGISTREERIDA!\n"
	.string "{CIRCLE_1} Ava VÕTMEESEMETE tasku.\n"
	.string "{CIRCLE_2} Vali võtmese, seejärel vali\n"
	.string "   REGISTREERI.$"

Help_Text_HowToUseBall::
	.string "{CIRCLE_1} Vali, et visata erililine POKé-\n"
	.string "   PALL, mida kasutatakse ainult SAFARIALAL.\n"
	.string "Kui metsikud POKéMONid ilmuvad, visa\n"
	.string "rohkesti SAFARIPALLE, et neid püüda!$"

Help_Text_HowToUseBait::
	.string "{CIRCLE_1} Vali, et visata erilist toitu,\n"
	.string "   mida kasutatakse ainult SAFARIALAL.\n"
	.string "See on POKéMONide toit, mähitud\n"
	.string "palliks lihtsaks söömiseks. Kui SÖÖT on\n"
	.string "visatud, võib metsik POKéMON\n"
	.string "sellest köituda ega pruugi põgeneda!$"

Help_Text_HowToUseRock::
	.string "{CIRCLE_1} Vali, et visata SAFARIALAL\n"
	.string "   maas lebav kivi.\n"
	.string "POKéMONile kivi viskamine võib\n"
	.string "ta põgenema panna, kuid\n"
	.string "muutub kergemini püüdavaks!$"

Help_Text_HowToUseHallOfFame::
	.string "{CIRCLE_1} Vali arvutis KUULSUSTEHALL.\n"
	.string "{CIRCLE_2} KUULSUSTEHALLI sisenenud\n"
	.string "   POKéMONe saab uurida.$"

Help_Text_HP::
	.string "EL$"

Help_Text_EXP::
	.string "KOG. {LEFT_PAREN}KOGEMUSEpunktid{RIGHT_PAREN}$"

Help_Text_Moves::
	.string "LIIGUTUSED$"

Help_Text_Attack::
	.string "RÜNNAK$"

Help_Text_Defense::
	.string "KAITSE$"

Help_Text_SpAtk::
	.string "ER. RÜN$"

Help_Text_SpDef::
	.string "ER. KAI$"

Help_Text_Speed::
	.string "KIIRUS$"

Help_Text_Level::
	.string "Ts. {LEFT_PAREN}Tase{RIGHT_PAREN}$"

Help_Text_Type::
	.string "TÜÜP$"

Help_Text_OT::
	.string "AT$"

Help_Text_Item::
	.string "ESE$"

Help_Text_Ability::
	.string "OSKUS$"

Help_Text_Money::
	.string "RAHA$"

Help_Text_MoveType::
	.string "LIIGUTUSE TÜÜP$"

Help_Text_Nature::
	.string "ISELOOM$"

Help_Text_IDNo::
	.string "ID nr.$"

Help_Text_PP::
	.string "JP$"

Help_Text_Power::
	.string "JÕUD$"

Help_Text_Accuracy::
	.string "TÄPSUS$"

Help_Text_FNT::
	.string "MIN$"

Help_Text_Items::
	.string "ESEMED$"

Help_Text_KeyItems::
	.string "VÕTMEESEMED$"

Help_Text_PokeBalls::
	.string "POKéPALLID$"

Help_Text_Pokedex::
	.string "POKéDEX$"

Help_Text_PlayTime::
	.string "MÄNGUAEG$"

Help_Text_Badges::
	.string "MÄRGID$"

Help_Text_TextSpeed::
	.string "TEKSTI KIIRUS$"

Help_Text_BattleScene::
	.string "LAHINGUVAADE$"

Help_Text_BattleStyle::
	.string "LAHINGUSTIIL$"

Help_Text_Sound::
	.string "HELI$"

Help_Text_ButtonMode::
	.string "NUPU REZIIM$"

Help_Text_Frame::
	.string "RAAM$"

Help_Text_Cancel2::
	.string "TÜHISTA$"

Help_Text_TM::
	.string "TM$"

Help_Text_HM::
	.string "HM$"

Help_Text_HMMove::
	.string "HM-i LIIGUTUS$"

Help_Text_Evolution::
	.string "EVOLUTSIOON$"

Help_Text_StatusProblem::
	.string "STAATUSPROBLEEM$"

Help_Text_Pokemon::
	.string "POKéMON$"

Help_Text_IDNo2::
	.string "ID nr.$"

Help_Text_Money2::
	.string "RAHA$"

Help_Text_Badges2::
	.string "MÄRGID$"

Help_Text_DefineHP::
	.string "EL näitab POKéMONi elujõudu.\n"
	.string "Kui POKéMONi EL langeb nullini,\l"
	.string "minestub ta ja ei suuda võidelda.\l"
	.string "Seega on lahingu võti proovida\l"
	.string "vaenlase EL nullini viia.\l"
	.string "Kui su POKéMONid on vigastatud, taasta\l"
	.string "nende EL POKéMONi KESKUSES või esemete abil.$"

Help_Text_DefineEXP::
	.string "KOGEMUSEpunktid on lühend sõnadest\n"
	.string "kogemuspunktid. POKéMONid teenivad\l"
	.string "kogemuspunkte, osaledes võidetud lahingutes.\l"
	.string "Kui POKéMON kogub piisavalt\l"
	.string "kogemuspunkte, tõuseb tema tase. KOGEMUSEriba\l"
	.string "näitab kogunenud punkte.\l"
	.string "Taseme tõustes läheb see nulliks.$"

Help_Text_DefineMoves::
	.string "POKéMONid võivad õppida kuni neli erinevat\n"
	.string "liigutust. On palju liigutuste liike,\l"
	.string "sealhulgas rünnakud ja erimõjuga\l"
	.string "liigutused. Õpitavate liigutuste liigid\l"
	.string "erinevad iga POKéMONi puhul.\l"
	.string "Mõnda liigutust saab õppida\l"
	.string "esemetelt.$"

Help_Text_DefineAttack::
	.string "RÜNNAK näitab rünnakuoskuse jõudu.\n"
	.string "Mida kõrgem see näitaja, seda\l"
	.string "võimsam on liigutus.\l"
	.string "Seda rakendatakse järgmiste liigutuste\l"
	.string "tüüpide puhul: TAVALINE, MÜRK, MAA,\l"
	.string "LENDAV, PUTUKAS, VÕITLEJA, KIVI, VAIM,\l"
	.string "ja TERAS.$"

Help_Text_DefineDefense::
	.string "KAITSE näitab POKéMONi vastupidavust\n"
	.string "füüsiliste rünnakute vastu.\l"
	.string "Mida kõrgem see näitaja, seda vähem\l"
	.string "kahju saadakse vaenlase füüsilisest löögist.$"

Help_Text_DefineSpAtk::
	.string "ER. RÜNNAK (Eriline Rünnak) näitab\n"
	.string "erirünnaku liigutuse jõudu.\l"
	.string "Mida kõrgem see näitaja, seda võimsam\l"
	.string "on erirünnaku liigutus.\l"
	.string "Seda rakendatakse järgmiste liigutuste\l"
	.string "tüüpide puhul: TULI, VESI, ELEKTER, ROHI,\l"
	.string "JÄÄ, PSÜÜHiKA, DRAAKON ja PIME.$"

Help_Text_DefineSpDef::
	.string "ER. KAITSE (Eriline Kaitse) näitab\n"
	.string "POKéMONi vastupidavust\l"
	.string "erir ü n n a k u t e  vastu.\l"
	.string "Mida kõrgem see näitaja, seda vähem\l"
	.string "kahju saadakse vaenlase erir ü n n a k u s t.$"

Help_Text_DefineSpeed::
	.string "KIIRUS näitab POKéMONi osavust.\n"
	.string "Kui see näitaja ületab vaenlase oma\l"
	.string "lahingus, saab POKéMON liigutuse teha\l"
	.string "enne oma aeglasemat vastast.$"

Help_Text_DefineLevel::
	.string "Ts. (Tase) näitab POKéMONi kasvu\n"
	.string "ja tugevust.\l"
	.string "Üldiselt tõusevad POKéMONi\l"
	.string "taseme tõustes tema näitajad nagu\l"
	.string "EL, RÜNNAK ja KAITSE, muutes ta tugevamaks.\l"
	.string "POKéMONid võivad taseme tõustes\l"
	.string "uue liigutuse selgeks õppida.$"

Help_Text_DefineType::
	.string "POKéMONid ja liigutused liigitatakse\n"
	.string "tüübi järgi. Igal tüübil on eelised ja\l"
	.string "puudused teiste tüüpide vastu.\l"
	.string "Näiteks, nagu kivi-paber-käärid mängus,\l"
	.string "on VESI tüüp tugev TULE tüübi vastu\l"
	.string "ja nõrk ROHU tüübi vastu.$"

Help_Text_DefineOT::
	.string "AT tähistab Algset TREENIJAT,\n"
	.string "esimest TREENIJAT, kes valitud\l"
	.string "POKéMONi püüdis.\l"
	.string "Isegi kui POKéMON vahetatakse, jääb\l"
	.string "AT nimi muutumatus.$"

Help_Text_DefineItem::
	.string "Kõiki POKéMONe saab panna hoidma\n"
	.string "ühte eset. Mõnda eset kasutab\l"
	.string "POKéMON automaatselt teatud\l"
	.string "olukordades. Et POKéMON eset hoiaks,\l"
	.string "vali ese KOTIST ja ANNA see\l"
	.string "POKéMONile.$"

Help_Text_DefineAbility::
	.string "Kõigil POKéMONidel on eriline OSKUS.\n"
	.string "Neid oskuseid on palju erinevaid,\l"
	.string "mõned kasutatavad lahingus, mõned\l"
	.string "mujal. Oskused erinevad\l"
	.string "liigiti. Mõnel liigil võib olla\l"
	.string "rohkem kui ühte liiki oskus.$"

Help_Text_DefineMoney::
	.string "Iga kord, kui võidad TREENIJAGA\n"
	.string "lahingu, saad auhinnaraha.\l"
	.string "Kogu auhinnaraha, et saaksid\l"
	.string "POKéMONi POODIDES nautida!$"

Help_Text_DefineMoveType::
	.string "Liigutused liigitatakse samuti tüüpide järgi.\n"
	.string "Kui teatud tüüpi POKéMON kasutab\l"
	.string "sama tüüpi liigutust, suureneb\l"
	.string "liigutuse jõud. Kui liigutuse tüübil\l"
	.string "on eelise vastavus sihtmärgi vastu,\l"
	.string "suureneb ka selle tõhusus.$"

Help_Text_DefineNature::
	.string "Kõigil POKéMONidel on isikupära\n"
	.string "ehk ISELOOM. POKéMONi\l"
	.string "iseloom näib mõjutavat, kuidas\l"
	.string "POKéMON tasemeid tõustes kasvab.$"

Help_Text_DefineIDNo::
	.string "ID nr. on spetsiaalne number, mis\n"
	.string "on sinule kui TREENIJALE omistatud.\l"
	.string "Koos AT nimega kasutatakse ID nr-i\l"
	.string "algse TREENIJA täpseks tuvastamiseks.\l"
	.string "ID nr. ei muutu isegi siis, kui\l"
	.string "POKéMON vahetatakse.$"

Help_Text_DefinePP::
	.string "JP tähistab Jõupunkte.\n"
	.string "See näitab, mitu korda saab\l"
	.string "teatud liigutust lahingus kasutada.\l"
	.string "Nagu EL, saab JP-d taastada\l"
	.string "külastades POKéMONi KESKUST\l"
	.string "või kasutades teatud esemeid.$"

Help_Text_DefinePower::
	.string "JÕUD näitab rünnaku tugevust.\n"
	.string "Mida suurem see number, seda\l"
	.string "suurem kahju saab vaenlasele\l"
	.string "põhjustada!$"

Help_Text_DefineAccuracy::
	.string "TÄPSUS näitab liigutuse\n"
	.string "vaenlase tabamise tõenäosust.\l"
	.string "Mida suurem see number, seda\l"
	.string "tõenäolisemalt liigutus tabab.$"

Help_Text_DefineFNT::
	.string "MIN tähistab minestunud.\n"
	.string "POKéMON minestub, kui tema EL\l"
	.string "langeb nullini. Ta ei suuda\l"
	.string "lahingus osaleda.\l"
	.string "Taasta minestunud POKéMON POKéMONi\l"
	.string "KESKUSES või kasuta eset.$"

Help_Text_DefineItems::
	.string "Igas POKéMONi POES ostetavad\n"
	.string "tavalised esemed pannakse ESEMETE taskusse.\l"
	.string "Esemeid saab kasutada, POKéMONile\l"
	.string "hoidmiseks anda või prügikasti visata.$"

Help_Text_DefineKeyItems::
	.string "Olulised esemed, mida leiad või\n"
	.string "inimestelt saad, pannakse\l"
	.string "VÕTMEESEMETE taskusse.\l"
	.string "Võtmesemeid saab kasutada või registreerida\l"
	.string "SELECT-ga koheseks kasutamiseks. Pärast\l"
	.string "registreerimist saab eset kasutada\l"
	.string "ilma MENÜÜD ja KOTTI avamata.$"

Help_Text_DefinePokeBalls::
	.string "POKéPALLID, mida kasutatakse\n"
	.string "metsikute POKéMONide püüdmiseks,\l"
	.string "pannakse POKéPALLIDE taskusse.\l"
	.string "POKéPALLE saab osta POKéMONi POODIDEST.\l"
	.string "Neid saab kasutada, POKéMONile\l"
	.string "hoidmiseks anda või prügikasti visata.$"

Help_Text_DefinePokedex::
	.string "See näitab, mitu POKéMONi liiki\n"
	.string "oled püüdnud ja/või evolutsiooniga\l"
	.string "POKéDEXi täitnud.\l"
	.string "Püüa kõvasti kõiksuguseid\l"
	.string "POKéMONe!$"

Help_Text_DefinePlayTime::
	.string "See on kogu aeg, mille oled\n"
	.string "selle mängu mängimisele kulutanud.$"

Help_Text_DefineBadges::
	.string "POKéMONi LIIGA MÄRGID, mille\n"
	.string "oled võitnud, registreeritakse ja\l"
	.string "kuvatakse. Teeni MÄRKE, alistades\l"
	.string "SAALIÜ L E M A ID erinevates linnades.$"

Help_Text_DefineTextSpeed::
	.string "Saad reguleerida, kui kiiresti\n"
	.string "tekst kuvatakse. Vali üks: AEGLANE,\l"
	.string "KESKMINE või KIIRE.$"

Help_Text_DefineBattleScene::
	.string "Saad valida, kas lahinguanimatsioon\n"
	.string "on SEES või VÄLJAS.$"

Help_Text_DefineBattleStyle::
	.string "Saad valida, kas TREENIJA saab\n"
	.string "vahetada POKéMONi pärast seda,\l"
	.string "kui see on vaenlase minestanud.\l"
	.string "Sea VAHETA peale, kui soovid\l"
	.string "võimalust POKéMONi vahetada pärast\l"
	.string "vaenlase minestamist.$"

Help_Text_DefineSound::
	.string "Saad valida MONO ja\n"
	.string "STEREO heliväljundi vahel.$"

Help_Text_DefineButtonMode::
	.string "Sea ABI peale, et kuvada abi\n"
	.string "vajutades L- või R-nuppu.\l"
	.string "Sea LR peale, et lubada\l"
	.string "POKéDEXi lehtede ja KOTI TASKUTE\l"
	.string "vahetamine L- ja R-nupu abil.\l"
	.string "Sea L=A peale, et L-nupp\l"
	.string "töötaks samamoodi kui A-nupp.$"

Help_Text_DefineFrame::
	.string "Saad valida teatud menüüde ümber\n"
	.string "oleva raami kujunduse. Proovi järele\l"
	.string "ja vaata, mis meeldib.$"

Help_Text_DefineCancel2::
	.string "Sätted muudetakse punasega\n"
	.string "näidatud valikuteks ja naased\l"
	.string "MENÜÜSSE.$"

Help_Text_DefineTM::
	.string "TM (Tehniline Masin) on seade,\n"
	.string "mida kasutatakse POKéMONile\l"
	.string "liigutuse õpetamiseks.\l"
	.string "Neid on palju erinevaid liike.\l"
	.string "Liigutusi saab õpetada ainult neile\l"
	.string "POKéMONidele, kes suudavad neid kasutada.\l"
	.string "TM puruneb pärast ühekordset kasutamist.$"

Help_Text_DefineHM::
	.string "HM (Peidetud Masin) on seade,\n"
	.string "mida kasutatakse POKéMONile\l"
	.string "PEIDETUD liigutuse õpetamiseks.\l"
	.string "PEIDETUD liigutust saab õpetada ainult\l"
	.string "neile POKéMONidele, kes suudavad seda kasutada.\l"
	.string "Erinevalt TM-ist saab HM-i kasutada\l"
	.string "ikka ja jälle. PEIDETUD liigutust\l"
	.string "on POKéMONil raske unustada.$"

Help_Text_DefineHMMove::
	.string "PEIDETUD liigutused on eriti olulised\n"
	.string "su seiklusele. Sellise liigutuse\l"
	.string "kasutamiseks väljaspool lahingut ava\l"
	.string "POKéMONi MENÜÜ ja lase seda\l"
	.string "liigutust tundval POKéMONil seda kasutada.\l"
	.string "Minestunud POKéMON võib kasutada\l"
	.string "PEIDETUD liigutust väljaspool lahingut.$"

Help_Text_DefineEvolution::
	.string "POKéMONide seas on neid, kes teatud\n"
	.string "tasemetele jõudes läbivad suuri muutusi\l"
	.string "(evolutsiooni). Evolutsioon põhjustab\l"
	.string "POKéMONi kuju muutumist, nime vahetust\l"
	.string "ja võib-olla ka õpitavate liigutuste\l"
	.string "muutumist. Mõned POKéMONid arenevad\l"
	.string "muudel põhjustel peale taseme tõusmise.$"

Help_Text_DefineStatusProblem::
	.string "Staatusprobleemid on järgmised:\n"
	.string "Uni: Ei saa liigutusi kasutada.\l"
	.string "Mürk: Põhjustab pidevat ELi kaotust.\l"
	.string "Halvatus: Võib liigutuste kasutamist takistada.\l"
	.string "Põletus: ELi kadu ja vähendab RÜNNAKUT.\l"
	.string "Külmutus: Ei saa liigutusi kasutada.\l"
	.string "Neid saab ravida esemetega jne.$"

Help_Text_DefinePokemon::
	.string "POKéMON on nimi, mida kasutatakse\n"
	.string "imeliste olendite kirjeldamiseks,\l"
	.string "kes elavad kõigis selle maailma\l"
	.string "nurkades. Inimesed kasvatavad\l"
	.string "POKéMONe lemmikloomadena,\l"
	.string "kasutavad neid võitluseks jne.$"

Help_Text_DefineIDNo2::
	.string "ID nr. on spetsiaalne number, mis\n"
	.string "on sinule kui TREENIJALE omistatud.\l"
	.string "Koos AT nimega kasutatakse ID nr-i\l"
	.string "algse TREENIJA täpseks tuvastamiseks.\l"
	.string "ID nr. ei muutu isegi siis, kui\l"
	.string "POKéMON vahetatakse.$"

Help_Text_DefineMoney2::
	.string "Iga kord, kui võidad TREENIJAGA\n"
	.string "lahingu, saad auhinnaraha.\l"
	.string "Kogu auhinnaraha, et saaksid\l"
	.string "POKéMONi POODIDES nautida!$"

Help_Text_DefineBadges2::
	.string "See näitab POKéMONi LIIGA MÄRKIDE\n"
	.string "arvu, mille oled võitnud.\l"
	.string "Teeni MÄRKE, alistades SAALIÜLEMAID\l"
	.string "erinevates linnades.$"

Help_Text_TheHelpSystem::
	.string "ABIsüsteem$"

Help_Text_TheGame::
	.string "Mäng$"

Help_Text_WirelessAdapter::
	.string "Juhtmevaba adapter$"

Help_Text_GameFundamentals1::
	.string "Mängu põhitõed 1$"

Help_Text_GameFundamentals2::
	.string "Mängu põhitõed 2$"

Help_Text_GameFundamentals3::
	.string "Mängu põhitõed 3$"

Help_Text_WhatArePokemon::
	.string "Mis on POKéMONid?$"

Help_Text_DescTheHelpSystem::
	.string "Abiinfo muutub vastavalt sellele,\n"
	.string "kui kaugele oled mängus jõudnud.\l"
	.string "Need on loodud sind toetama,\l"
	.string "kui neid vajad. Kui on midagi,\l"
	.string "mida ei mõista, otsi üles ABIsüsteem!$"

Help_Text_DescTheGame::
	.string "Sa saad peategelaseks, et\n"
	.string "uurida POKéMONi maailma!\l"
	.string "Inimestega rääkides ja mõistatusi\l"
	.string "lahendades avanevad sulle uued teed.\l"
	.string "Püüdle eesmärgi poole koos oma\l"
	.string "suurepäraste POKéMONidega!$"

Help_Text_DescWirelessAdapter::
	.string "See mäng suhtleb juhtmevaba\n"
	.string "ühenduse kaudu juhtmevaba adapteriga.\p"
	.string "Ole juhtmevaba igal ajal, igal pool\n"
	.string "ja kõigiga!\p"
	.string "Proovi mängida juhtmevaba adapteriga\n"
	.string "alati ühendatuna!$"

Help_Text_DescGameFundamentals1::
	.string "Külasta iga linna ja alevit, läbi\n"
	.string "iga tee, uuri iga koobast ja\l"
	.string "võta iga väljakutse vastu,\l"
	.string "et pürgida suurimaks POKéMONide\l"
	.string "TREENIJAKS!$"

Help_Text_DescGameFundamentals2::
	.string "Oma seiklusel seisad silmitsi\n"
	.string "paljude takistustega. Iga takistuse\l"
	.string "saab ületada midagi tehes\l"
	.string "või mõistatusi lahendades. Mõnda\l"
	.string "takistust mõjutab miski, mis juhtub\l"
	.string "kaugel.$"

Help_Text_DescGameFundamentals3::
	.string "Mõned su teel olevad takistused\n"
	.string "saab eemaldada, kui su POKéMONid\l"
	.string "õpivad selgeks kindlad liigutused.$"

Help_Text_DescWhatArePokemon::
	.string "POKéMONid on imelised olendid,\n"
	.string "kes on mõistatuste hõlmas. Neid võid\l"
	.string "kohata kõikjal maailmas… pikas\l"
	.string "rohus, koopastes, meres ja mujal.\l"
	.string "Nad näivad kasvavat kuulekaks\l"
	.string "neid püüdnud TREENIJATELE.$"

Help_Text_UsingTypeMatchupList::
	.string "Tüüpide vastavuste nimekirja kasutamine$"

Help_Text_OwnMoveDark::
	.string "Oma liigutuse tüüp: PIME$"

Help_Text_OwnPokemonDark::
	.string "Oma POKéMONi tüüp: PIME$"

Help_Text_OwnMoveRock::
	.string "Oma liigutuse tüüp: KIVI$"

Help_Text_OwnPokemonRock::
	.string "Oma POKéMONi tüüp: KIVI$"

Help_Text_OwnMovePsychic::
	.string "Oma liigutuse tüüp: PSÜÜHiKA$"

Help_Text_OwnPokemonPsychic::
	.string "Oma POKéMONi tüüp: PSÜÜHiKA$"

Help_Text_OwnMoveFighting::
	.string "Oma liigutuse tüüp: VÕITLEJA$"

Help_Text_OwnPokemonFighting::
	.string "Oma POKéMONi tüüp: VÕITLEJA$"

Help_Text_OwnMoveGrass::
	.string "Oma liigutuse tüüp: ROHI$"

Help_Text_OwnPokemonGrass::
	.string "Oma POKéMONi tüüp: ROHI$"

Help_Text_OwnMoveGhost::
	.string "Oma liigutuse tüüp: VAIM$"

Help_Text_OwnPokemonGhost::
	.string "Oma POKéMONi tüüp: VAIM$"

Help_Text_OwnMoveIce::
	.string "Oma liigutuse tüüp: JÄÄ$"

Help_Text_OwnPokemonIce::
	.string "Oma POKéMONi tüüp: JÄÄ$"

Help_Text_OwnMoveGround::
	.string "Oma liigutuse tüüp: MAA$"

Help_Text_OwnPokemonGround::
	.string "Oma POKéMONi tüüp: MAA$"

Help_Text_OwnMoveElectric::
	.string "Oma liigutuse tüüp: ELEKTER$"

Help_Text_OwnPokemonElectric::
	.string "Oma POKéMONi tüüp: ELEKTER$"

Help_Text_OwnMovePoison::
	.string "Oma liigutuse tüüp: MÜRK$"

Help_Text_OwnPokemonPoison::
	.string "Oma POKéMONi tüüp: MÜRK$"

Help_Text_OwnMoveDragon::
	.string "Oma liigutuse tüüp: DRAAKON$"

Help_Text_OwnPokemonDragon::
	.string "Oma POKéMONi tüüp: DRAAKON$"

Help_Text_OwnMoveNormal::
	.string "Oma liigutuse tüüp: TAVALINE$"

Help_Text_OwnPokemonNormal::
	.string "Oma POKéMONi tüüp: TAVALINE$"

Help_Text_OwnMoveSteel::
	.string "Oma liigutuse tüüp: TERAS$"

Help_Text_OwnPokemonSteel::
	.string "Oma POKéMONi tüüp: TERAS$"

Help_Text_OwnMoveFlying::
	.string "Oma liigutuse tüüp: LENDAV$"

Help_Text_OwnPokemonFlying::
	.string "Oma POKéMONi tüüp: LENDAV$"

Help_Text_OwnMoveFire::
	.string "Oma liigutuse tüüp: TULI$"

Help_Text_OwnPokemonFire::
	.string "Oma POKéMONi tüüp: TULI$"

Help_Text_OwnMoveWater::
	.string "Oma liigutuse tüüp: VESI$"

Help_Text_OwnPokemonWater::
	.string "Oma POKéMONi tüüp: VESI$"

Help_Text_OwnMoveBug::
	.string "Oma liigutuse tüüp: PUTUKAS$"

Help_Text_OwnPokemonBug::
	.string "Oma POKéMONi tüüp: PUTUKAS$"

Help_Text_HowToUseTypeMatchupList::
	.string "Sõltuvalt liigutuse tüübi ja\n"
	.string "sihtmärk-POKéMONi tüübi vastavusest\l"
	.string "varieerub liigutuse tõhusus:\l"
	.string "{CIRCLE_DOT}: Väga tõhus!\l"
	.string "{TRIANGLE}: Mitte eriti tõhus\l"
	.string "{BIG_MULT_X}: Ei mõju üldse\l"
	.string "(Muudel vastavustel muutusi pole.)$"

Help_Text_TypeMatchupOwnMoveDark::
	.string "Mõju vastase POKéMONile:\p"
	.string "   {CIRCLE_DOT}: PSÜÜHiKA, VAIM\p"
	.string "   {TRIANGLE}: VÕITLEJA, PIME, TERAS$"

Help_Text_TypeMatchupOwnPokemonDark::
	.string "Vaenlase liigutuse mõju oma POKéMONile:\p"
	.string "   {CIRCLE_DOT}: VÕITLEJA, PUTUKAS\p"
	.string "   {TRIANGLE}: VAIM, PIME\p"
	.string "   {BIG_MULT_X}: PSÜÜHiKA$"

Help_Text_TypeMatchupOwnMoveRock::
	.string "Mõju vastase POKéMONile:\p"
	.string "   {CIRCLE_DOT}: TULI, JÄÄ, LENDAV, PUTUKAS\p"
	.string "   {TRIANGLE}: VÕITLEJA, MAA, TERAS$"

Help_Text_TypeMatchupOwnPokemonRock::
	.string "Vaenlase liigutuse mõju oma POKéMONile:\p"
	.string "   {CIRCLE_DOT}: VESI, ROHI, VÕITLEJA,\n"
	.string "       MAA, TERAS\p"
	.string "   {TRIANGLE}: TAVALINE, TULI, MÜRK, LENDAV$"

Help_Text_TypeMatchupOwnMovePsychic::
	.string "Mõju vastase POKéMONile:\p"
	.string "   {CIRCLE_DOT}: VÕITLEJA, MÜRK\p"
	.string "   {TRIANGLE}: PSÜÜHiKA, TERAS\p"
	.string "   {BIG_MULT_X}: PIME$"

Help_Text_TypeMatchupOwnPokemonPsychic::
	.string "Vaenlase liigutuse mõju oma POKéMONile:\p"
	.string "   {CIRCLE_DOT}: PUTUKAS, VAIM, PIME\p"
	.string "   {TRIANGLE}: VÕITLEJA, PSÜÜHiKA$"

Help_Text_TypeMatchupOwnMoveFighting::
	.string "Mõju vastase POKéMONile:\p"
	.string "   {CIRCLE_DOT}: TAVALINE, JÄÄ, KIVI, PIME, TERAS\p"
	.string "   {TRIANGLE}: MÜRK, LENDAV, PSÜÜHiKA, PUTUKAS\p"
	.string "   {BIG_MULT_X}: VAIM$"

Help_Text_TypeMatchupOwnPokemonFighting::
	.string "Vaenlase liigutuse mõju oma POKéMONile:\p"
	.string "   {CIRCLE_DOT}: LENDAV, PSÜÜHiKA\p"
	.string "   {TRIANGLE}: PUTUKAS, KIVI, PIME$"

Help_Text_TypeMatchupOwnMoveGrass::
	.string "Mõju vastase POKéMONile:\p"
	.string "   {CIRCLE_DOT}: VESI, MAA, KIVI\p"
	.string "   {TRIANGLE}: TULI, ROHI, MÜRK, LENDAV,\n"
	.string "       PUTUKAS, DRAAKON, TERAS$"

Help_Text_TypeMatchupOwnPokemonGrass::
	.string "Vaenlase liigutuse mõju oma POKéMONile:\p"
	.string "   {CIRCLE_DOT}: TULI, JÄÄ, MÜRK, LENDAV, PUTUKAS\p"
	.string "   {TRIANGLE}: VESI, ELEKTER, ROHI, MAA$"

Help_Text_TypeMatchupOwnMoveGhost::
	.string "Mõju vastase POKéMONile:\p"
	.string "   {CIRCLE_DOT}: PSÜÜHiKA, VAIM\p"
	.string "   {TRIANGLE}: PIME, TERAS\p"
	.string "   {BIG_MULT_X}: TAVALINE$"

Help_Text_TypeMatchupOwnPokemonGhost::
	.string "Vaenlase liigutuse mõju oma POKéMONile:\p"
	.string "   {CIRCLE_DOT}: VAIM, PIME\p"
	.string "   {TRIANGLE}: MÜRK, PUTUKAS\p"
	.string "   {BIG_MULT_X}: TAVALINE, VÕITLEJA$"

Help_Text_TypeMatchupOwnMoveIce::
	.string "Mõju vastase POKéMONile:\p"
	.string "   {CIRCLE_DOT}: ROHI, MAA, LENDAV, DRAAKON\p"
	.string "   {TRIANGLE}: TULI, VESI, JÄÄ, TERAS$"

Help_Text_TypeMatchupOwnPokemonIce::
	.string "Vaenlase liigutuse mõju oma POKéMONile:\p"
	.string "   {CIRCLE_DOT}: TULI, VÕITLEJA, KIVI, TERAS\p"
	.string "   {TRIANGLE}: JÄÄ$"

Help_Text_TypeMatchupOwnMoveGround::
	.string "Mõju vastase POKéMONile:\p"
	.string "   {CIRCLE_DOT}: TULI, ELEKTER, MÜRK, KIVI,\n"
	.string "       TERAS\p"
	.string "   {TRIANGLE}: ROHI, PUTUKAS\n"
	.string "   {BIG_MULT_X}: LENDAV$"

Help_Text_TypeMatchupOwnPokemonGround::
	.string "Vaenlase liigutuse mõju oma POKéMONile:\p"
	.string "   {CIRCLE_DOT}: VESI, ROHI, JÄÄ\p"
	.string "   {TRIANGLE}: MÜRK, KIVI\p"
	.string "   {BIG_MULT_X}: ELEKTER$"

Help_Text_TypeMatchupOwnMoveElectric::
	.string "Mõju vastase POKéMONile:\p"
	.string "   {CIRCLE_DOT}: VESI, LENDAV\p"
	.string "   {TRIANGLE}: ELEKTER, ROHI, DRAAKON\p"
	.string "   {BIG_MULT_X}: MAA$"

Help_Text_TypeMatchupOwnPokemonElectric::
	.string "Vaenlase liigutuse mõju oma POKéMONile:\p"
	.string "   {CIRCLE_DOT}: MAA\p"
	.string "   {TRIANGLE}: ELEKTER, LENDAV, TERAS$"

Help_Text_TypeMatchupOwnMovePoison::
	.string "Mõju vastase POKéMONile:\p"
	.string "   {CIRCLE_DOT}: ROHI\p"
	.string "   {TRIANGLE}: MÜRK, MAA, KIVI, VAIM\p"
	.string "   {BIG_MULT_X}: TERAS$"

Help_Text_TypeMatchupOwnPokemonPoison::
	.string "Vaenlase liigutuse mõju oma POKéMONile:\p"
	.string "   {CIRCLE_DOT}: MAA, PSÜÜHiKA\p"
	.string "   {TRIANGLE}: ROHI, VÕITLEJA, MÜRK, PUTUKAS$"

Help_Text_TypeMatchupOwnMoveDragon::
	.string "Mõju vastase POKéMONile:\p"
	.string "   {CIRCLE_DOT}: DRAAKON\p"
	.string "   {TRIANGLE}: TERAS$"

Help_Text_TypeMatchupOwnPokemonDragon::
	.string "Vaenlase liigutuse mõju oma POKéMONile:\p"
	.string "   {CIRCLE_DOT}: JÄÄ, DRAAKON\p"
	.string "   {TRIANGLE}: TULI, VESI, ELEKTER, ROHI$"

Help_Text_TypeMatchupOwnMoveNormal::
	.string "Mõju vastase POKéMONile:\p"
	.string "   {TRIANGLE}: KIVI, TERAS\p"
	.string "   {BIG_MULT_X}: VAIM$"

Help_Text_TypeMatchupOwnPokemonNormal::
	.string "Vaenlase liigutuse mõju oma POKéMONile:\p"
	.string "   {CIRCLE_DOT}: VÕITLEJA\p"
	.string "   {BIG_MULT_X}: VAIM$"

Help_Text_TypeMatchupOwnMoveSteel::
	.string "Mõju vastase POKéMONile:\p"
	.string "   {CIRCLE_DOT}: JÄÄ, KIVI\p"
	.string "   {TRIANGLE}: TULI, VESI, ELEKTER, TERAS$"

Help_Text_TypeMatchupOwnPokemonSteel::
	.string "Vaenlase liigutuse mõju oma POKéMONile:\p"
	.string "   {CIRCLE_DOT}: TULI, VÕITLEJA, MAA\n"
	.string "   {TRIANGLE}: TAVALINE, ROHI, JÄÄ, LENDAV,\l"
	.string "       PSÜÜHiKA, PUTUKAS, KIVI, VAIM,\l"
	.string "       DRAAKON, PIME, TERAS\l"
	.string "   {BIG_MULT_X}: MÜRK$"

Help_Text_TypeMatchupOwnMoveFlying::
	.string "Mõju vastase POKéMONile:\p"
	.string "   {CIRCLE_DOT}: ROHI, VÕITLEJA, PUTUKAS\p"
	.string "   {TRIANGLE}: ELEKTER, KIVI, TERAS$"

Help_Text_TypeMatchupOwnPokemonFlying::
	.string "Vaenlase liigutuse mõju oma POKéMONile:\p"
	.string "   {CIRCLE_DOT}: ELEKTER, JÄÄ, KIVI\p"
	.string "   {TRIANGLE}: ROHI, VÕITLEJA, PUTUKAS\p"
	.string "   {BIG_MULT_X}: MAA$"

Help_Text_TypeMatchupOwnMoveFire::
	.string "Mõju vastase POKéMONile:\p"
	.string "   {CIRCLE_DOT}: ROHI, JÄÄ, PUTUKAS, TERAS\p"
	.string "   {TRIANGLE}: TULI, VESI, KIVI, DRAAKON$"

Help_Text_TypeMatchupOwnPokemonFire::
	.string "Vaenlase liigutuse mõju oma POKéMONile:\p"
	.string "   {CIRCLE_DOT}: VESI, MAA, KIVI\p"
	.string "   {TRIANGLE}: TULI, ROHI, JÄÄ, PUTUKAS, TERAS$"

Help_Text_TypeMatchupOwnMoveWater::
	.string "Mõju vastase POKéMONile:\p"
	.string "   {CIRCLE_DOT}: TULI, MAA, KIVI\p"
	.string "   {TRIANGLE}: VESI, ROHI, DRAAKON$"

Help_Text_TypeMatchupOwnPokemonWater::
	.string "Vaenlase liigutuse mõju oma POKéMONile:\p"
	.string "   {CIRCLE_DOT}: ELEKTER, ROHI\p"
	.string "   {TRIANGLE}: TULI, VESI, JÄÄ, TERAS$"

Help_Text_TypeMatchupOwnMoveBug::
	.string "Mõju vastase POKéMONile:\p"
	.string "   {CIRCLE_DOT}: ROHI, PSÜÜHiKA, PIME\p"
	.string "   {TRIANGLE}: TULI, VÕITLEJA, MÜRK,\n"
	.string "       LENDAV, VAIM, TERAS$"

Help_Text_TypeMatchupOwnPokemonBug::
	.string "Vaenlase liigutuse mõju oma POKéMONile:\p"
	.string "   {CIRCLE_DOT}: TULI, LENDAV, KIVI\p"
	.string "   {TRIANGLE}: ROHI, VÕITLEJA, MAA$"
