Trade_Text_LookingForMonWannaTradeForMon::
	.string "Otsin POKéMONi\n"
	.string "nimega {STR_VAR_1}!\p"
	.string "Kas vahetaksid selle minu\n"
	.string "{STR_VAR_2} vastu?$"

Trade_Text_AwwOhWell::
	.string "Ahh!\n"
	.string "No, mis teha…$"

Trade_Text_WhatThatsNoMon::
	.string "Mis?\n"
	.string "See pole {STR_VAR_1}!$"

Trade_Text_HeyThanks::
	.string "Hei, aitäh!$"

Trade_Text_IsntMyOldMonGreat::
	.string "Kas mu endine {STR_VAR_2} pole suurepärane?$"

Trade_Text_DoYouHaveMonWouldYouTradeForMon::
	.string "Tere! Kas sul juhtumisi\n"
	.string "on {STR_VAR_1}?\p"
	.string "Kas nõustuksid vahetama\n"
	.string "selle minu {STR_VAR_2} vastu?$"

Trade_Text_WellIfYouDontWantTo::
	.string "Noh, kui sa ei taha…$"

Trade_Text_ThisIsntMon::
	.string "Hmm?\n"
	.string "See pole {STR_VAR_1}.\p"
	.string "Mõtle minule, kui leiad ühe.$"

Trade_Text_Thanks::
	.string "Aitäh!$"

Trade_Text_HasTradedMonGrownStronger::
	.string "See {STR_VAR_2}, kelle sulle vahetasin\n"
	.string "- kas ta on tugevamaks kasvanud?$"

Trade_Text_DoYouHaveMonWantToTradeForMon::
	.string "Hei!\n"
	.string "Kas sul on {STR_VAR_1}?\p"
	.string "Kas tahaksid vahetada selle\n"
	.string "minu {STR_VAR_2} vastu?$"

Trade_Text_ThatsTooBad::
	.string "Kahju küll.$"

Trade_Text_ThisIsNoMon::
	.string "…See pole {STR_VAR_1}.\p"
	.string "Kui leiad ühe, vaheta minuga.$"

Trade_Text_ThanksYoureAPal::
	.string "Aitäh, sa oled tõeline sõber!$"

Trade_Text_HowIsMyOldMon::
	.string "Kuidas läheb mu endisel {STR_VAR_2}-l?\n"
	.string "Minu {STR_VAR_1} on väga heas vormis!$"
