gOtherText_NewName::
    .string "UUS NIMI$"

gNameChoice_Green::
    .string "KALEV$"

gNameChoice_Red::
    .string "TAAVI$"

gNameChoice_Leaf::
    .string "ARGO$"

gNameChoice_Fire::
    .string "TIIT$"

gNameChoice_Gary::
    .string "SIIM$"

gNameChoice_Kaz::
    .string "ANDRES$"

gNameChoice_Toru::
    .string "TÕNU$"

gNameChoice_Ash::
    .string "AADU$"

gNameChoice_Kene::
    .string "JAAN$"

gNameChoice_Geki::
    .string "TOOMAS$"

gNameChoice_Jak::
    .string "JAAK$"

gNameChoice_Janne::
    .string "TARMO$"

gNameChoice_Jonn::
    .string "TIMO$"

gNameChoice_Kamon::
    .string "OSKAR$"

gNameChoice_Karl::
    .string "MIHKEL$"

gNameChoice_Taylor::
    .string "JÜRI$"

gNameChoice_Oscar::
    .string "ARTUR$"

gNameChoice_Hiro::
    .string "ANTON$"

gNameChoice_Max::
    .string "ARVO$"

gNameChoice_Jon::
    .string "VAHUR$"

gNameChoice_Ralph::
    .string "AHTI$"

gNameChoice_Kay::
    .string "MARKO$"

gNameChoice_Tosh::
    .string "PEETER$"

gNameChoice_Roak::
    .string "VIKTOR$"

gNameChoice_Omi::
    .string "MARI$"

gNameChoice_Jodi::
    .string "HUDA$"

gNameChoice_Amanda::
    .string "MARIKA$"

gNameChoice_Hillary::
    .string "AIRE$"

gNameChoice_Makey::
    .string "EVA$"

gNameChoice_Michi::
    .string "ELLI$"

gNameChoice_Paula::
    .string "GERLI$"

gNameChoice_June::
    .string "GERTU$"

gNameChoice_Cassie::
    .string "HALVI$"

gNameChoice_Rey::
    .string "LIISU$"

gNameChoice_Seda::
    .string "HELENE$"

gNameChoice_Kiko::
    .string "KIRKE$"

gNameChoice_Mina::
    .string "MIINA$"

gNameChoice_Norie::
    .string "NORA$"

gNameChoice_Sai::
    .string "SIRJE$"

gNameChoice_Momo::
    .string "MARLEEN$"

gNameChoice_Suzi::
    .string "KERSTI$"

gControlsGuide_Text_Intro::
    .string "Erinevaid nuppe selgitatakse nende\n"
    .string "tähtsuse järjekorras.$"

gControlsGuide_Text_DPad::
    .string "Liigutab peategelast.\n"
    .string "Kasutatakse ka erinevate\n"
    .string "andmevalikute valimiseks.$"

gControlsGuide_Text_AButton::
    .string "Kasutatakse valiku kinnitamiseks,\n"
    .string "asjade kontrollimiseks, vestlemiseks\n"
    .string "ja teksti kerimiseks.$"

gControlsGuide_Text_BButton::
    .string "Kasutatakse väljumiseks, valiku\n"
    .string "tühistamiseks ja reziimi\n"
    .string "tühistamiseks.$"

gControlsGuide_Text_StartButton::
    .string "Vajuta seda nuppu, et avada\n"
    .string "MENÜÜD.$"

gControlsGuide_Text_SelectButton::
    .string "Kasutatakse esemete liigutamiseks\n"
    .string "ja registreeritud eseme\n"
    .string "kasutamiseks.$"

gControlsGuide_Text_LRButtons::
    .string "Kui vajad abi mängu mängimiseks\n"
    .string "või kuidas asju teha,\n"
    .string "siis vajuta L või R nuppu.$"

gOakSpeech_Text_AskPlayerGender::
    .string "Nüüd ütle mulle. Kas sa oled poiss?\n"
    .string "Või oled sa tüdruk?$"

gPikachuIntro_Text_Page1::
    .string "Maailmas, kuhu sa varsti minema\n"
    .string "hakkad, ootab sind suur\n"
    .string "seiklus, kus sina oled kangelane.\n"
    .string "\n"
    .string "Räägi inimestega ja kontrolli asju\n"
    .string "kõikjal, kuhu lähed - linnades,\n"
    .string "teedel või koobastes. Kogu\n"
    .string "informatsiooni ja vihjeid igast allikast.$"

gPikachuIntro_Text_Page2::
    .string "Uued teed avanevad sulle, kui aitad\n"
    .string "abivajajaid, ületad väljakutseid ja\n"
    .string "lahendad müsteeriume.\n"
    .string "\n"
    .string "Mõnikord kutsuvad sind lahingule\n"
    .string "teised treenerid ja ründavad sind\n"
    .string "metsikud olendid. Ole vaprak ja jätka edasi.$"

gPikachuIntro_Text_Page3::
    .string "Sinu seikluse käigus loodame, et\n"
    .string "suhtled igasuguste inimestega ja\n"
    .string "saavutad isiklikku kasvu.\n"
    .string "See on meie suurim eesmärk.\n"
    .string "\n"
    .string "Vajuta A nuppu ja alusta\n"
    .string "oma seiklust!$"

gOakSpeech_Text_WelcomeToTheWorld::
    .string "Tervist!\n"
    .string "Meeldiv tutvuda!\p"
    .string "Tere tulemast POKéMONide maailma!\p"
    .string "Minu nimi on TAMM.\p"
    .string "Inimesed kutsuvad mind\n"
    .string "kiindunult POKéMON PROFESSORIKS.\p$"

gOakSpeech_Text_ThisWorld::
    .string "Seda maailma…$"

gOakSpeech_Text_IsInhabitedFarAndWide::
    .string "…asustavad laialdaselt olendid,\n"
    .string "keda nimetatakse POKéMONiks.\p$"

gOakSpeech_Text_IStudyPokemon::
    .string "Mõnede inimeste jaoks on POKéMONid\n"
    .string "koduloomad. Teised kasutavad neid\n"
    .string "võitlemiseks.\p"
    .string "Aga mina…\p"
    .string "uurin POKéMONe ametialaselt.\p$"    

gOakSpeech_Text_TellMeALittleAboutYourself::
    .string "Aga kõigepealt räägi mulle natuke\n"
    .string "enda kohta.\p$"

gOakSpeech_Text_YourNameWhatIsIt::
    .string "Alustame su nimega.\n"
    .string "Mis see on?\p$"

gOakSpeech_Text_SoYourNameIsPlayer::
    .string "Hea küll…\n"
    .string "Niisiis su nimi on {PLAYER}.$"

gOakSpeech_Text_WhatWasHisName::
    .string "See on minu pojapoeg.\p"
    .string "Ta on olnud su rivaal sellest ajast,\n"
    .string "kui te mõlemad olite veel beebid.\p"
    .string "…Hmm, mis oli tema nimi?$"

gOakSpeech_Text_YourRivalsNameWhatWasIt::
    .string "Su rivaali nimi, mis see oli?$"

gOakSpeech_Text_ConfirmRivalName::
    .string "…Äh, kas see oli {RIVAL}?$"

gOakSpeech_Text_RememberRivalsName::
    .string "Õige! Nüüd mäletan!\n"
    .string "Tema nimi on {RIVAL}!\p$"

gOakSpeech_Text_LetsGo::
    .string "{PLAYER}!\p"
    .string "Sinu enda POKéMONi legend on\n"
    .string "kohe algamas!\p"
    .string "POKéMONiga seotud unistuste ja\n"
    .string "seikluste maailm ootab sind! Lähme!$"
