Text_ObtainedTheX::
	.string "Said {STR_VAR_2} kätte!$"

Text_BagIsFull::
	.string "KOTT on täis…$"

Text_PutItemAway::
	.string "{PLAYER} pani {STR_VAR_2}\n"
	.string "{STR_VAR_3}-sse.$"

Text_FoundOneItem::
	.string "{PLAYER} leidis ühe {STR_VAR_2}'i!$"

Text_TooBadBagFull::
	.string "Kahju küll!\n"
	.string "KOTT on täis…$"

Text_FoundXCoins::
	.string "{PLAYER} leidis\n"
	.string "{STR_VAR_1} {STR_VAR_2}!$"

Text_PutCoinsAwayInCoinCase::
	.string "{PLAYER} pani MÜNDI MÜNDIKARPI\n"

Text_CoinCaseIsFull::
	.string "Kahju küll!\n"
	.string "MÜNDIKARP on täis…$"

Text_NothingToPutThemIn::
	.string "Kahju küll!\n"
	.string "Ei saa neid kuhugi panna…$"

Text_FoundXItems::
	.string "{PLAYER} leidis\n"
	.string "{STR_VAR_1} {STR_VAR_2}(s)!$"

Text_ObtainedTheDecor::
	.string "Said {STR_VAR_2}'i kätte!$"

Text_NoRoomForAnotherDecor::
	.string "Kahju! Ruumi pole enam\n"
	.string "teise {STR_VAR_2} jaoks…$"

Text_DecorTransferredToPC::
	.string "{STR_VAR_2} viidi üle\n"
	.string "ARVUTISSE.$"
