Text_MonSentToBoxInSomeonesPC::
    .string "{STR_VAR_2} saadeti\n"
    .string "Kellegi arvutisse.\p"
    .string "See paigutati\n"
    .string "KASTI {STR_VAR_1}.$"

Text_MonSentToBoxInBillsPC::
    .string "{STR_VAR_2} saadeti\n"
    .string "BILLI arvutisse.\p"
    .string "See paigutati\n"
    .string "KASTI {STR_VAR_1}.$"

Text_MonSentToBoxSomeonesBoxFull::
    .string "KAST {STR_VAR_3} Kellegi\n"
    .string "arvutis oli täis.\p"
    .string "{STR_VAR_2} saadeti\n"
    .string "KASTI {STR_VAR_1}.$"

Text_MonSentToBoxBillsBoxFull::
    .string "KAST {STR_VAR_3} BILLI\n"
    .string "arvutis oli täis.\p"
    .string "{STR_VAR_2} saadeti\n"
    .string "KASTI {STR_VAR_1}.$"

Text_PlayerObtainedTheMon::
    .string "{PLAYER} sai\n"
    .string "{STR_VAR_1}!$"

@ Unused. Translated below
@ You cannot carry any more Pokemon, so {STR_VAR_2} was sent to PC Box {STR_VAR_1}!
Text_MonSentToBoxInPC::
    .string "ポケモンを　もちきれないので\n"
    .string "パソコンの　ボックス“{STR_VAR_1}”　に\l"
    .string "{STR_VAR_2}を　てんそうした！$"

Text_NoMoreRoomForPokemon::
    .string "There's no more room for POKéMON!\p"
    .string "The POKéMON BOXES are full and\n"
    .string "can't accept any more!$"
