Text_MayIHelpYou::
 	.string "Tere, seal!\n"
	.string "Kas ma saan teid aidata?$"

Text_FillOutQuestionnaire::
 	.string "Siin on küsimustik.\n"
	.string "Kas sooviksite selle täita?$"

Text_QuestionnaireThankYou::
 	.string "Tänan, et võtsite aega meie\n"
	.string "küsimustiku täitmiseks.\p"
	.string "Teie tagasisidet säilitatakse\n"
	.string "hilisemaks kasutamiseks.$"

Text_YouKnowThoseWords::
	.string "Oh, tere!\n"
	.string "Te teate neid sõnu?\p"
	.string "See tähendab, et te peate teadma\n"
	.string "SALAPÄRASE KINGI kohta.\p"
	.string "Nüüdsest peaksite\n"
	.string "SALAPÄRASEID KINKE saama!$"

Text_YouCanAccessMysteryGift::
 	.string "Kui olete mängu salvestanud, saate\n"
	.string "SALAPÄRASE KINKI kasutada.$"

Text_ThankYouForAccessingMysteryGift::
	.string "Tänan SALAPÄRASE KINGI\n"
	.string "süsteemi kasutamise eest.$"
