PokedexRating_Text_HowIsPokedexComingAlong::
.string "OAK: Rõõm näha!\n"
.string "Kuidas su POKéDEX edeneb?\p"
.string "Nii, lase mul pilk peale visata.$"

PokedexRating_Text_SeenXOwnedY::
.string "Sinu edusammud POKéDEXi\n"
.string "täitmisel on järgmised:\p"
.string "{STR_VAR_1} POKéMONi nähtud ja\n"
.string "{STR_VAR_2} POKéMONi püütud.\p"
.string "{FONT_NORMAL}PROF. OAKi hinnang:$"

PokedexRating_Text_LessThan10::
.string "Sul on veel palju teha.\p"
.string "Käi läbi iga viimnegi muruplats,\n"
.string "mis ette jääb, ja otsi POKéMONe!$"

PokedexRating_Text_LessThan20::
.string "Tundub, et oled jõudmas\n"
.string "õigele teele!\p"
.string "Andsin ühele oma ASSISTENDILE FLASH\n"
.string "HMi. Vaata, et sa sellele kindlasti järele lähed!$"

PokedexRating_Text_LessThan30::
.string "Su POKéDEX vajaks veel veidi\n"
.string "rohkem mahtu!\p"
.string "Proovi püüda teisi POKéMONi\n"
.string "liike!$"

PokedexRating_Text_LessThan40::
.string "Hea, näha on, et sa\n"
.string "annad endast parima!\p"
.string "Andsin ühele oma ASSISTENDILE\n"
.string "ITEMFINDERi. Võta see kindlasti vastu!$"

PokedexRating_Text_LessThan50::
.string "Su POKéDEX edeneb juba\n"
.string "päris hästi!\p"
.string "Andsin ühele oma ASSISTENDILE\n"
.string "AMULET COINi. Hoolitse selle eest, et sa selle kätte saad!$"

PokedexRating_Text_LessThan60::
.string "Ah, sa oled lõpuks ületanud 50\n"
.string "liigi piiri!\p"
.string "Andsin ühele oma ASSISTENDILE EXP.\n"
.string "SHARE'i. Mine kindlasti võta see ära!$"

PokedexRating_Text_LessThan70::
.string "Ohoo! Sellest on saamas juba päris\n"
.string "austusväärne POKéDEX!$"

PokedexRating_Text_LessThan80::
.string "Väga hea!\p"
.string "Ma arvan, et leiad veelgi rohkem\n"
.string "POKéMONe, kui kalale lähed!$"

PokedexRating_Text_LessThan90::
.string "Suurepärane! Las ma arvan… Sulle\n"
.string "meeldib asju koguda, eks ju?$"

PokedexRating_Text_LessThan100::
.string "Ma olen rabatud!\n"
.string "Selle saavutamine pidas küll raske olema!$"

PokedexRating_Text_LessThan110::
.string "Sa jõudsid lõpuks 100 liigini!\n"
.string "Ma ei suuda uskuda, kui osav sa oled!$"

PokedexRating_Text_LessThan120::
.string "Sul on olemas isegi POKéMONide\n"
.string "arenenud vormid! Super!$"

PokedexRating_Text_LessThan130::
.string "Suurepärane! Vaheta sõpradega,\n"
.string "et veelgi rohkem juurde saada!$"

PokedexRating_Text_LessThan140::
.string "Silmapaistev!\n"
.string "Sinust on saanud selles asjas tõeline pro!$"

PokedexRating_Text_LessThan150::
.string "Mul polegi midagi enam öelda!\n"
.string "Nüüd oled sina hoopis POKéMONi PROFESSOR!$"

PokedexRating_Text_Complete::
.string "Su POKéDEX on täiesti valmis!\n"
.string "Palju õnne!!$"

PokedexRating_Text_NationalDexSeenXOwnedY::
.string "Ja sinu NATIONAL POKéDEX on:\p"
.string "{STR_VAR_1} POKéMONi nähtud ja\n"
.string "{STR_VAR_2} POKéMONi püütud.$"

PokedexRating_Text_LookForwardToFilledNationalDex::
.string "Jään põnevusega ootama, kuni sa\n"
.string "ka NATIONAL POKéDEXi täis saad!$"

PokedexRating_Text_YouveCompletedDex::
.string "Lõpuks ometi…\p"
.string "Sa oled viimaks ometi täitnud terve\n"
.string "POKéDEXi!\p"
.string "See on suurepärane!\n"
.string "Tõesti, see on erakordne saavutus!$"

PokedexRating_Text_Wroooaaarrr::
.string "Wroooooooaaaaaarrrr!$"

PokedexRating_Text_HaHa::
.string "Haa haa‥$"

PokedexRating_Text_ThankYouMadeDreamReality::
.string "Aitäh sulle, {PLAYER}!\n"
.string "Südamest, aitäh!\l"
.string "Sa tegid minu unistuse teoks!$"

PokedexRating_Text_LoveSeeingYourPokedex::
.string "OAK: Ah, tere tulemast!\p"
.string "Ütle mulle, kuidas su POKéDEX\n"
.string "edeneb?\p"
.string "Wahaha!\p"
.string "Tegelikult ma küll tean, kuidas seis on, aga mulle\n"
.string "lihtsalt nii väga meeldib seda vaadata!\p"
.string "Nii, näita ette…$"
