Text_OnlySkilledTrainersAllowedThrough::
	.string "Only truly skilled TRAINERS are\n"
	.string "allowed through.\p"
	.string "You don't have the {STR_VAR_1}\n"
	.string "yet!$"
	.string "Ainult tõeliselt osavad TREENRID\n"
	.string "saavad siit läbi. Teil ei ole veel\n"
	.string "{STR_VAR_1}!$"

Text_CantLetYouPass::
 	.string "Reeglid on reeglid.\n"
	.string "Ma ei saa teid läbi lasta.$"

Text_OhThatsBadgeGoRightAhead::
	.string "Nonii! See on {STR_VAR_1}!\n"
	.string "Minge otse edasi.$"

Text_OnlyPassWithBadgeDontHaveYet::
	.string "Te saate siit läbi minna ainult siis,\n"
	.string "kui teil on {STR_VAR_1}. Te ei ole {STR_VAR_1}\n"
	.string "veel saanud. Teil on seda vaja, et jõuda\n"
	.string "POKéMONi LIIGAsse.$"

Text_OnlyPassWithBadgeOhGoAhead::
	.string "Te saate siit läbi minna ainult siis,\n"
	.string "kui teil on {STR_VAR_1} olemas.\n"
	.string "See on {STR_VAR_1}!{PAUSE_MUSIC}{PLAY_BGM}{MUS_LEVEL_UP}{PAUSE 0x60}{RESUME_MUSIC} Noh siis...\n"
	.string "Palun, minge otse edasi.$"