gText_WouldYouLikeToSaveTheGame::
	.string "Kas sooviksite mängu salvestada?$"

gText_AlreadySaveFile_WouldLikeToOverwrite::
	.string "Salvestusfail on juba olemas.\n"
	.string "Kas seda võib üle kirjutada?$"

gText_SavingDontTurnOffThePower::
	.string "SALVESTAMINE…\n"
	.string "ÄRGE LÜLITAGE TOITET VÄLJA.$"

gText_PlayerSavedTheGame::
	.string "{PLAYER} salvestas mängu.$"

gText_SaveFailed2::
	.string "セーブに　しっぱい　しました‥$"

gText_DifferentGameFile::
	.string "WARNING!\p"
	.string "There is a different game file that\n"
	.string "is already saved.\p"
	.string "If you save now, the other file's\n"
	.string "adventure, including items and\l"
	.string "POKéMON, will be entirely lost.\p"
	.string "Are you sure you want to save now\n"
	.string "and overwrite the other save file?$"
