Text_FirstShouldRestoreMonsHealth::
	.string "Kõigepealt taasta oma\n"
	.string "POKéMONide tervis täielikult.$"

Text_MonsHealedShouldBuyPotions::
	.string "Teie POKéMONid on täielikult\n"
	.string "terveks ravitud.\p"
	.string "Kui teie POKéMONide energia,\n"
	.string "ehk TE, langeb, tulge meie juurde.\p"
	.string "Kui plaanite kaugele minna,\n"
	.string "ostke POKéMONI POEST\l"
	.string "JOOKE varude täiendamiseks.\p"
	.string "Soovime teile edu!$"

Text_MonsHealed::
	.string "Teie POKéMONid on täielikult\n"
	.string "terveks ravitud.\p"
	.string "Soovime teile edu!$"

Text_HadQuiteAnExperienceTakeRest::
	.string "EMA: {PLAYER}!\n"
	.string "Tere tulemast koju.\p"
	.string "Tundub, et sul oli päris\n"
	.string "põnev seiklus.\p"
	.string "Võib-olla peaksid veidi\n"
	.string "puhkama.$"

Text_MomExplainHPGetPotions::
	.string "EMA: Oh, tore! Sina ja su\n"
	.string "POKéMONid näete väga head välja.\p"
	.string "Prof. TAMM helistas mulle.\p"
	.string "Ta ütles, et POKéMONide energiat\n"
	.string "mõõdetakse TE-s.\p"
	.string "Kui su POKéMONid kaotavad TE,\n"
	.string "saad nad terveks ravida igas\l"
	.string "POKéMONI KESKUSES.\p"
	.string "Kui lähed kaugele rändama,\n"
	.string "targas TREENIJA ostab\l"
	.string "JOOKE POKéMONI POEST.\p"
	.string "Tee mulle au, kallis!\p"
	.string "Hoolitse enda eest!$"

Text_WhitedOutLostMoney::
	.string "{PLAYER}il ei ole enam\n"
	.string "võitlusvõimelisi POKéMONe!\p"
	.string "{PLAYER} sattus paanikasse ja kaotas ¥{STR_VAR_1}…\p"
	.string "… … … …\p"
	.string "{PLAYER} kukkus minestusse!$"

Text_WhitedOut::
	.string "{PLAYER}il ei ole enam\n"
	.string "võitlusvõimelisi POKéMONe!\p"
	.string "{PLAYER} kukkus minestusse!$"
